import random

"""
self-dmg 1: fixed recoil
self-dmg 2: gains x% of dmg it inflicted
self-dmg 3: gains x% of its max hp
self-dmg 4: loses x% of dmg it inflicted
self-dmg 5: loses x% of its max hp
"""

moves = {
    "Absorb":{
        'power': 20,
        'pktype': 'Grass',
        'acc': 100,
        'selfdmg': {'2':50},
        'pp': 25,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Acid":{
        'power': 40,
        'pktype': 'Poison',
        'acc': 100,
        'selfdmg': {},
        'pp': 30,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,-1,0],
        'raiser': [0,0,0],
        'eraiser': [0,20,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Acid Armor":{
        'power': 0,
        'pktype': 'Poison',
        'acc': 100,
        'selfdmg': {},
        'pp': 20,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,1,0],
        'eraise': [0,0,0],
        'raiser': [0,100,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Acid Spray":{
        'power': 0,
        'pktype': 'Poison',
        'acc': 100,
        'selfdmg': {},
        'pp': 20,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,2,0],
        'raiser': [0,0,0],
        'eraiser': [0,100,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Aerial Ace":{
        'power': 60,
        'pktype': 'Flying',
        'acc': 100,
        'selfdmg': {},
        'pp': 20,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Aeroblast":{
        'power': 100,
        'pktype': 'Flying',
        'acc': 95,
        'selfdmg': {},
        'pp': 5,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 1,
        'priority': 0,
        'status': ['',0]
    },
    "Agility":{
        'power': 0,
        'pktype': 'Psychic',
        'acc': 100,
        'selfdmg': {},
        'pp': 30,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,2],
        'eraise': [0,0,0],
        'raiser': [0,0,100],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Air Cutter":{
        'power': 60,
        'pktype': 'Flying',
        'acc': 100,
        'selfdmg': {},
        'pp': 20,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 1,
        'priority': 0,
        'status': ['',0]
    },
    "Amnesia":{
        'power': 0,
        'pktype': 'Psychic',
        'acc': 100,
        'selfdmg': {},
        'pp': 20,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,2,0],
        'eraise': [0,0,0],
        'raiser': [0,100,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Anchor Shot":{
        'power': 80,
        'pktype': 'Steel',
        'acc': 100,
        'selfdmg': {},
        'pp': 20,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Ancient Power":{
        'power': 60,
        'pktype': 'Ground',
        'acc': 100,
        'selfdmg': {},
        'pp': 5,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [1,1,1],
        'eraise': [0,0,0],
        'raiser': [100,100,100],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Aqua Jet":{
        'power': 40,
        'pktype': 'Water',
        'acc': 100,
        'selfdmg': {},
        'pp': 20,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 1,
        'status': ['',0]
    },
    "Aqua Ring":{
        'power': 40,
        'pktype': 'Water',
        'acc': 100,
        'selfdmg': {'3':6.25},
        'pp': 20,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Aqua Tail":{
        'power': 90,
        'pktype': 'Water',
        'acc': 90,
        'selfdmg': {},
        'pp': 10,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Arm Thrust":{
        'power': 15,
        'pktype': 'Fighting',
        'acc': 100,
        'selfdmg': {},
        'pp': 20,
        'recharge': False,
        'charge': 0,
        'timesperturn': [2,5],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Assurance":{
        'power': 60,
        'pktype': 'Dark',
        'acc': 100,
        'selfdmg': {},
        'pp': 20,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 1,
        'status': ['',0]
    },
    "Astonish":{
        'power': 30,
        'pktype': 'Ghost',
        'acc': 100,
        'selfdmg': {},
        'pp': 15,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 30,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Attack Order":{
        'power': 90,
        'pktype': 'Bug',
        'acc': 100,
        'selfdmg': {},
        'pp': 15,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 1,
        'priority': 0,
        'status': ['',0]
    },
    "Aura Sphere":{
        'power': 80,
        'pktype': 'Fighting',
        'acc': 100,
        'selfdmg': {},
        'pp': 20,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Aurora Beam":{
        'power': 65,
        'pktype': 'Ice',
        'acc': 100,
        'selfdmg': {},
        'pp': 20,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [-1,0,0],
        'raiser': [0,0,0],
        'eraiser': [10,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Autotomize":{
        'power': 0,
        'pktype': 'Steel',
        'acc': 0,
        'selfdmg': {},
        'pp': 15,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,2],
        'eraise': [0,0,0],
        'raiser': [0,0,100],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Baby-Doll Eyes":{
        'power': 0,
        'pktype': 'Fairy',
        'acc': 100,
        'selfdmg': {},
        'pp': 30,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [-1,0,0],
        'raiser': [0,0,0],
        'eraiser': [100,0,0],
        'flinch': 0,
        'crithit': 1,
        'priority': 0,
        'status': ['',0]
    },
    "Barrage":{
        'power': 15,
        'pktype': 'Normal',
        'acc': 85,
        'selfdmg': {},
        'pp': 20,
        'recharge': False,
        'charge': 0,
        'timesperturn': [2,5],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Belch":{
        'power': 120,
        'pktype': 'Poison',
        'acc': 90,
        'selfdmg': {},
        'pp': 10,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Belly Drum":{
        'power': 0,
        'pktype': 'Normal',
        'acc': 100,
        'selfdmg': {'4':50},
        'pp': 10,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [6,0,0],
        'eraise': [0,0,0],
        'raiser': [100,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Bite":{
        'power': 60,
        'pktype': 'Dark',
        'acc': 100,
        'selfdmg': {},
        'pp': 25,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 30,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Blast Burn":{
        'power': 150,
        'pktype': 'Fire',
        'acc': 100,
        'selfdmg': {},
        'pp': 5,
        'recharge': True,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Blaze Kick":{
        'power': 85,
        'pktype': 'Fire',
        'acc': 90,
        'selfdmg': {},
        'pp': 10,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 1,
        'priority': 0,
        'status': ['bur',10]
    },
    "Blue Flare":{
        'power': 130,
        'pktype': 'Fire',
        'acc': 85,
        'selfdmg': {},
        'pp': 5,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['bur',20]
    },
    "Body Slam":{
        'power': 85,
        'pktype': 'Normal',
        'acc': 100,
        'selfdmg': {},
        'pp': 15,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['par',30]
    },
    "Bolt Strike":{
        'power': 130,
        'pktype': 'Electric',
        'acc': 85,
        'selfdmg': {},
        'pp': 5,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['par',20]
    },
    "Bone Club":{
        'power': 65,
        'pktype': 'Ground',
        'acc': 85,
        'selfdmg': {},
        'pp': 20,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 10,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Bone Rush":{
        'power': 25,
        'pktype': 'Normal',
        'acc': 90,
        'selfdmg': {},
        'pp': 10,
        'recharge': False,
        'charge': 0,
        'timesperturn': [2,5],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Bonemerang":{
        'power': 50,
        'pktype': 'Normal',
        'acc': 90,
        'selfdmg': {},
        'pp': 10,
        'recharge': False,
        'charge': 0,
        'timesperturn': [2,2],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Boomburst":{
        'power': 140,
        'pktype': 'Normal',
        'acc': 100,
        'selfdmg': {'1':140},
        'pp': 10,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Brave Bird":{
        'power': 120,
        'pktype': 'Flying',
        'acc': 100,
        'selfdmg': {'4':33.3333333333333333333333333},
        'pp': 15,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Bubble":{
        'power': 40,
        'pktype': 'Water',
        'acc': 100,
        'selfdmg': {},
        'pp': 30,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,-1],
        'raiser': [0,0,0],
        'eraiser': [0,0,10],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Bubble Beam":{
        'power': 65,
        'pktype': 'Water',
        'acc': 100,
        'selfdmg': {},
        'pp': 20,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,-1],
        'raiser': [0,0,0],
        'eraiser': [0,0,10],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Bug Bite":{
        'power': 70,
        'pktype': 'Bug',
        'acc': 100,
        'selfdmg': {},
        'pp': 20,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Bug Buzz":{
        'power': 90,
        'pktype': 'Bug',
        'acc': 100,
        'selfdmg': {},
        'pp': 10,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,-1],
        'raiser': [0,0,0],
        'eraiser': [0,0,10],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Bulk Up":{
        'power': 0,
        'pktype': 'Fighting',
        'acc': 100,
        'selfdmg': {},
        'pp': 20,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [1,1,0],
        'eraise': [0,0,0],
        'raiser': [100,100,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Bullet Punch":{
        'power': 40,
        'pktype': 'Steel',
        'acc': 100,
        'selfdmg': {},
        'pp': 20,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 1,
        'status': ['',0]
    },
    "Charge":{
        'power': 0,
        'pktype': 'Electric',
        'acc': 100,
        'selfdmg': {},
        'pp': 20,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [1,1,0],
        'eraise': [0,0,0],
        'raiser': [100,100,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Charm":{
        'power': 0,
        'pktype': 'Fairy',
        'acc': 100,
        'selfdmg': {},
        'pp': 20,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [-2,0,0],
        'raiser': [0,0,0],
        'eraiser': [100,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Chatter":{
        'power': 65,
        'pktype': 'Flying',
        'acc': 100,
        'selfdmg': {},
        'pp': 20,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['con',50]
    },
    "Chip Away":{
        'power': 100,
        'pktype': 'Normal',
        'acc': 100,
        'selfdmg': {},
        'pp': 20,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Circle Throw":{
        'power': 80,
        'pktype': 'Fighting',
        'acc': 90,
        'selfdmg': {},
        'pp': 10,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': -6,
        'status': ['',0]
    },
    "Close Combat":{
        'power': 120,
        'pktype': 'Fighting',
        'acc': 100,
        'selfdmg': {},
        'pp': 5,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,-1,0],
        'eraise': [0,0,0],
        'raiser': [0,100,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Coil":{
        'power': 0,
        'pktype': 'Poison',
        'acc': 0,
        'selfdmg': {},
        'pp': 20,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [1,1,0],
        'eraise': [0,0,0],
        'raiser': [100,100,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Comet Punch":{
        'power': 18,
        'pktype': 'Normal',
        'acc': 85,
        'selfdmg': {},
        'pp': 20,
        'recharge': False,
        'charge': 0,
        'timesperturn': [2,5],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Confuse Ray":{
        'power': 0,
        'pktype': 'Ghost',
        'acc': 100,
        'selfdmg': {},
        'pp': 10,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['con',100]
    },
    "Confusion":{
        'power': 50,
        'pktype': 'Psychic',
        'acc': 100,
        'selfdmg': {},
        'pp': 25,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['con',10]
    },
    "Constrict":{
        'power': 10,
        'pktype': 'Normal',
        'acc': 100,
        'selfdmg': {},
        'pp': 35,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,-1,0],
        'raiser': [0,0,0],
        'eraiser': [0,10,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Cosmic Power":{
        'power': 0,
        'pktype': 'Psychic',
        'acc': 100,
        'selfdmg': {},
        'pp': 20,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,1,0],
        'eraise': [0,0,0],
        'raiser': [0,100,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Cotton Guard":{
        'power': 0,
        'pktype': 'Grass',
        'acc': 100,
        'selfdmg': {},
        'pp': 10,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,3,0],
        'eraise': [0,0,0],
        'raiser': [0,100,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Cotton Spore":{
        'power': 0,
        'pktype': 'Psychic',
        'acc': 100,
        'selfdmg': {},
        'pp': 40,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,-2],
        'raiser': [0,0,0],
        'eraiser': [0,0,100],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Crabhammer":{
        'power': 100,
        'pktype': 'Water',
        'acc': 90,
        'selfdmg': {},
        'pp': 10,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 1,
        'priority': 0,
        'status': ['',0]
    },
    "Cross Chop":{
        'power': 100,
        'pktype': 'Fighting',
        'acc': 80,
        'selfdmg': {},
        'pp': 5,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 1,
        'priority': 0,
        'status': ['',0]
    },
    "Crunch":{
        'power': 80,
        'pktype': 'Dark',
        'acc': 100,
        'selfdmg': {},
        'pp': 15,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,-1,0],
        'raiser': [0,0,0],
        'eraiser': [0,20,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Crush Claw":{
        'power': 75,
        'pktype': 'Normal',
        'acc': 95,
        'selfdmg': {},
        'pp': 10,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,-1,0],
        'raiser': [0,0,0],
        'eraiser': [0,50,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Cut":{
        'power': 50,
        'pktype': 'Normal',
        'acc': 95,
        'selfdmg': {},
        'pp': 30,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Dark Void":{
        'power': 0,
        'pktype': 'Dark',
        'acc': 50,
        'selfdmg': {},
        'pp': 15,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['sle',100]
    },
    "Defence Order":{
        'power': 0,
        'pktype': 'Bug',
        'acc': 100,
        'selfdmg': {},
        'pp': 15,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,1,0],
        'eraise': [0,0,0],
        'raiser': [0,100,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Defence Curl":{
        'power': 0,
        'pktype': 'Normal',
        'acc': 100,
        'selfdmg': {},
        'pp': 40,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,1,0],
        'eraise': [0,0,0],
        'raiser': [0,100,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Diamond Storm":{
        'power': 100,
        'pktype': 'Ground',
        'acc': 95,
        'selfdmg': {},
        'pp': 5,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,2,0],
        'eraise': [0,0,0],
        'raiser': [0,50,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Disarming Voice":{
        'power': 40,
        'pktype': 'Water',
        'acc': 100,
        'selfdmg': {},
        'pp': 15,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Discharge":{
        'power': 80,
        'pktype': 'Electric',
        'acc': 100,
        'selfdmg': {},
        'pp': 15,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['par',30]
    },
    "Dive":{
        'power': 80,
        'pktype': 'Water',
        'acc': 100,
        'selfdmg': {},
        'pp': 15,
        'recharge': False,
        'charge': 1,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Dizzy Punch":{
        'power': 70,
        'pktype': 'Normal',
        'acc': 100,
        'selfdmg': {},
        'pp': 10,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['con',20]
    },
    "Double Hit":{
        'power': 35,
        'pktype': 'Normal',
        'acc': 90,
        'selfdmg': {},
        'pp': 10,
        'recharge': False,
        'charge': 0,
        'timesperturn': [2,2],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Double Kick":{
        'power': 30,
        'pktype': 'Fighting',
        'acc': 100,
        'selfdmg': {},
        'pp': 30,
        'recharge': False,
        'charge': 0,
        'timesperturn': [2,2],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Double Slap":{
        'power': 15,
        'pktype': 'Normal',
        'acc': 85,
        'selfdmg': {},
        'pp': 10,
        'recharge': False,
        'charge': 0,
        'timesperturn': [2,5],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    },
    "Double-Edge":{
        'power': 120,
        'pktype': 'Normal',
        'acc': 100,
        'selfdmg': {'4':33.3333333333333333333333333},
        'pp': 15,
        'recharge': False,
        'charge': 0,
        'timesperturn': [1,1],
        'raise': [0,0,0],
        'eraise': [0,0,0],
        'raiser': [0,0,0],
        'eraiser': [0,0,0],
        'flinch': 0,
        'crithit': 0,
        'priority': 0,
        'status': ['',0]
    }
}

class Move():
    name = ''
    power = 0
    pktype = ''
    accuracy = 0
    selfdmg = 0
    pp = 0
    recharge = False
    charge = 0
    timesperturn = []
    atkraise = 0
    defraise = 0
    spdraise = 0
    enemyatkraise = 0
    enemydefraise = 0
    enemyspdraise = 0
    atkraiserate = 0
    defraiserate = 0
    spdraiserate = 0
    enemyatkraiserate = 0
    enemydefraiserate = 0
    enemyspdraiserate = 0
    flinchrate = 0
    addcritrate = 0
    addpriority = 0
    statuschange = ''

    def __init__(self,name:str):
        self.name = name
        self.power = moves[name]['power']
        self.pktype = moves[name]['pktype']
        self.accuracy = moves[name]['acc']
        self.selfdmg = moves[name]['recoil']
        self.pp = moves[name]['pp']
        self.recharge = moves[name]['recharge']
        self.charge = moves[name]['charge']
        self.timesperturn = moves[name]['timesperturn']
        self.atkraise,self.defraise,self.spdraise = moves[name]['raise']
        self.enemyatkraise,self.enemydefraise,self.ememyspdraise = moves[name]['eraise']
        self.atkraiserate,self.defraiserate,self.spdraiserate = moves[name]['raiser']
        self.enemyatkraiserate,self.enemydefraiserate,self.ememyspdraiserate = moves[name]['eraiser']
        self.flinchrate = moves[name]['flinch']
        self.addcritrate = moves[name]['crithit']
        self.addpriority = moves[name]['priority']
        self.statuschange = moves[name]['status']

    def __str__(self):
        return str(self.__dict__)