compatible = {
    '001': {
        'Growl':1,
        'Tackle':1,
        'Vine Whip':5,
        'Poison Powder':14,
        'Sleep Powder':14,
        'Take Down':18,
        'Razor Leaf':23,
        'Growth':27,
        'Double-Edge':32
    },
    '002': {
        'Growl':1,
        'Tackle':1,
        'Vine Whip':1,
        'Poison Powder':1,
        'Sleep Powder':1,
        'Take Down':22,
        'Razor Leaf':31,
        'Growth':39,
        'Double-Edge':48,
        'Solar Beam':56
    },
    '003': {
        'Amnesia':1,
        'Growl':1,
        'Tackle':1,
        'Vine Whip':1,
        'Poison Powder':1,
        'Sleep Powder':1,
        'Petal Blizzard':1,
        'Petal Dance':1,
        'Power Whip':1,
        'Take Down':1,
        'Razor Leaf':1,
        'Growth':44,
        'Double-Edge':58,
        'Solar Beam':71
    },
    '004': {
        'Growl':1,
        'Scratch':1,
        'Smokescreen':9,
        'Ember':13,
        'Fury Swipes':18,
        'Slash':31,
        'Flamethrower':36
    },
    '005': {
        'Ember':1,
        'Growl':1,
        'Scratch':1,
        'Smokescreen':1,
        'Fury Swipes':20,
        'Slash':39,
        'Flamethrower':46
    },
    '006': {
        'Crunch':1,
        'Ember':1,
        'Growl':1,
        'Heat Wave':1,
        'Scratch':1,
        'Smokecreen':1,
        'Wing Attack':1,
        'Fury Swipes':1,
        'Fire Spin':1,
        'Slash':43,
        'Flamethrower':54,
        'Air Slash':62,
        'Flare Blitz':75
    },
    '007':{
        'Tackle':1,
        'Tail Whip':5,
        'Bubble':9,
        'Withdraw':14,
        'Water Gun':19,
        'Bite':23,
        'Bubble Beam':27,
        'Headbutt':36,
        'Hydro Pump':41,
        'Skull Bash':45
    },
    '008':{
        'Tackle':1,
        'Tail Whip':1,
        'Bubble':1,
        'Withdraw':1,
        'Water Gun':20,
        'Bite':27,
        'Bubble Beam':33,
        'Headbutt':46,
        'Hydro Pump':53,
        'Skull Bash':59
    },
    '009':{
        'Aqua Jet':1,
        'Tackle':1,
        'Fake Out':1,
        'Flash Cannon':1,
        'Tail Whip':1,
        'Bubble':1,
        'Withdraw':1,
        'Water Gun':1,
        'Bite':1,
        'Bubble Beam':1,
        'Headbutt':54,
        'Hydro Pump':65,
        'Skull Bash':75
    },
    '010':{
        'Tackle':1,
        'String Shot':1
    },
    '011':{
        'Harden':1
    },
    '012':{
        'Confusion':1,
        'Gust':1,
        'Poison Powder':13,
        'Sleep Powder':13,
        'Stun Spore':13,
        'Psybeam':16,
        'Supersonic':19,
        'Quiver Dance':22,
        'Air Slash':28,
        'Bug Buzz':31
    },
    '013':{
        'Poison Sting':1,
        'String Shot':1
    },
    '014':{
        'Harden':1
    },
    '015':{
        'Twineedle':1,
        'Peck':1,
        'Rage':13,
        'Fury Attack':16,
        'Poison Jab':22,
        'Agility':25,
        'Pin Missile':28,
        'Outrage':31
    },
    '016':{
        'Tackle':1,
        'Sand Attack':3,
        'Gust':5,
        'Quick Attack':11,
        'Wing Attack':15,
        'Roost':17,
        'Agility':23,
        'Air Slash':27,
        'Razor Wind':31
    },
    '017':{
        'Tackle':1,
        'Sand Attack':1,
        'Gust':1,
        'Quick Attack':11,
        'Wing Attack':1,
        'Roost':1,
        'Agility':31,
        'Air Slash':39,
        'Razor Wind':45
    },
    '018':{
        'Heat Wave':1,
        'Tackle':1,
        'Sand Attack':1,
        'Gust':1,
        'Quick Attack':1,
        'Sky Attack':1,
        'Wing Attack':1,
        'Roost':1,
        'Agility':1,
        'Air Slash':43,
        'Razor Wind':53
    },
    '019':{
        'Tackle':1,
        'Tail Whip':3,
        'Quick Attack':6,
        'Bite':12,
        'Crunch':18,
        'Hyper Fang':21,
        'Sucker Punch':24,
        'Double-Edge':27
    },
    '020':{
        'Tackle':1,
        'Tail Whip':1,
        'Quick Attack':1,
        'Fury Swipes':1,
        'Swords Dance':1,
        'Bite':1,
        'Crunch':1,
        'Hyper Fang':26,
        'Sucker Punch':34,
        'Double-Edge':42
    },
    '021':{
        'Peck':1,
        'Growl':3,
        'Leer':8,
        'Fury Attack':16,
        'Roost':24,
        'Agility':27,
        'Drill Peck':32
    },
    '022':{
        'Drill Run':1,
        'Growl':1,
        'Leer':1,
        'Peck':1,
        'Quick Attack':1,
        'Sky Attack':1,
        'Fury Attack':1,
        'Roost':29,
        'Agility':37,
        'Drill Peck':47
    },
    '023':{
        'Poison Sting':1,
        'Leer':4,
        'Acid':8,
        'Bite':12,
        'Glare':20,
        'Poison Jab':24,
        'Slam':28,
        'Screech':32,
        'Toxic':36
    },
    '024':{
        'Crunch':1,
        'Poison Sting':1,
        'Leer':1,
        'Acid':1,
        'Sucker Punch':1,
        'Bite':1,
        'Glare':1,
        'Poison Jab':28,
        'Slam':36,
        'Screech':44,
        'Toxic':52
    },
    '025':{
        'Growl':1,
        'Thunder Shock':1,
        'Tail Whip':3,
        'Quick Attack':6,
        'Double Kick':9,
        'Thunder Wave':15,
        'Thunderbolt':21,
        'Slam':24,
        'Agility':27,
        'Thunder':30
    },
    '026':{
        'Discharge':1,
        'Fake Out':1,
        'Growl':1,
        'Nuzzle':1,
        'Quick Attack':1,
        'Spark':1,
        'Tail Whip':1,
        'Thunder Wave':1,
        'Thunder Punch':1,
        'Thunder Shock':1,
        'Thunderbolt':1,
        'Thunder':1
    },
    '027':{
        'Defence Curl':1,
        'Scratch':1,
        'Poison Sting':4,
        'Sand Attack':8,
        'Swift':12,
        'Fury Swipes':16,
        'Dig':20,
        'Swords Dance':28,
        'Slash':32,
        'Earthquake':36
    },
    '028':{
        'Defence Curl':1,
        'Scratch':1,
        'Poison Sting':1,
        'Sand Attack':1,
        'Swift':1,
        'Fury Swipes':1,
        'Dig':1,
        'Swords Dance':36,
        'Slash':44,
        'Earthquake':52
    },
    '029':{
        'Growl':1,
        'Scratch':1,
        'Tail Whip':3,
        'Poison Sting':6,
        'Double Kick':9,
        'Bite':12,
        'Toxic':18,
        'Fury Swipes':21,
        'Crunch':24
    },
    '030':{
        'Growl':1,
        'Scratch':1,
        'Tail Whip':1,
        'Poison Sting':1,
        'Double Kick':1,
        'Bite':1,
        'Toxic':23,
        'Fury Swipes':31,
        'Crunch':39
    },
    '031':{
        'Body Slam':1,
        'Growl':1,
        'Scratch':1,
        'Poison Sting':1,
        'Supersonic':1,
        'Tail Whip':1,
        'Superpower':55
    },
    '032':{
        'Leer':1,
        'Peck':1,
        'Poison Sting':3,
        'Double Kick':6,
        'Horn Attack':12,
        'Toxic':18,
        'Fury Attack':21,
        'Poison Jab':24,
        'Horn Drill':27
    },
    '033':{
        'Leer':1,
        'Peck':1,
        'Poison Sting':1,
        'Double Kick':1,
        'Horn Attack':1,
        'Toxic':23,
        'Fury Attack':31,
        'Poison Jab':39,
        'Horn Drill':47,
    },
    '034':{
        'Leer':1,
        'Peck':1,
        'Poison Sting':1,
        'Supersonic':1,
        'Thrash':1,
        'Megahorn':55
    },
    '035':{
        'Growl':1,
        'Pound':1,
        'Defence Curl':4,
        'Sing':6,
        'Double Slap':12,
        'Amnesia':16,
        'Body Slam':24,
        'Moonblast':28
    },
    '036':{
        'Growl':1,
        'Pound':1,
        'Defence Curl':1,
        'Sing':1,
        'Charm':1,
        'Cosmic Power':1,
        'Meteor Mash':1,
        'Moonblast':1,
        'Splash':1,
        'Stored Power':1,
        'Sweet Kiss':1
    },
    '037':{
        'Tackle':1,
        'Tail Whip':3,
        'Ember':7,
        'Quick Attack':10,
        'Confuse Ray':14,
        'Will-O-Wisp':17,
        'Flamethrower':24,
        'Fire Blast':31
    },
    '038':{
        'Confuse Ray':1,
        'Ember':1,
        'Hypnosis':1,
        'Nasty Plot':1,
        'Quick Attack':1,
        'Tackle':1,
        'Tail Whip':1,
        'Fire Blast':1,
        'Flamethrower':1,
        'Incinerate':1,
        'Inferno':1,
        'Will-O-Wisp':1
    },
    '039':{
        'Sing':1,
        'Pound':4,
        'Defence Curl':6,
        'Double Slap':12,
        'Rest':18,
        'Body Slam':22,
        'Double-Edge':28
    },
    '040':{
        'Body Slam':1,
        'Charm':1,
        'Covet':1,
        'Defence Curl':1,
        'Disarming Voice':1,
        'Double-Edge':1,
        'Echoed Voice':1,
        'Hyper Voice':1,
        'Play Rough':1,
        'Pound':1,
        'Rest':1,
        'Round':1,
        'Sing':1,
        'Sweet Kiss':1
    },
    '041':{
        'Absorb':1,
        'Supersonic':1,
        'Wing Attack':4,
        'Bite':9,
        'Swift':12,
        'Confuse Ray':17,
        'Leech Life':25,
        'Toxic':28,
        'Air Slash':33
    },
    '042':{
        'Absorb':1,
        'Crunch':1,
        'Quick Attack':1,
        'Supersonic':1,
        'Wing Attack':1,
        'Bite':1,
        'Swift':1,
        'Confuse Ray':1,
        'Leech Life':31,
        'Toxic':40,
        'Air Slash':51
    },
    '043':{
        'Absorb':1,
        'Growth':4,
        'Acid':8,
        'Poison Powder':12,
        'Stun Spore':13,
        'Sleep Powder':14,
        'Razor Leaf':18,
        'Mega Drain':22,
        'Toxic':26,
        'Moonblast':30
    },
    '044':{
        'Absorb':1,
        'Growth':1,
        'Acid':1,
        'Poison Powder':1,
        'Stun Spore':1,
        'Sleep Powder':1,
        'Razor Leaf':1,
        'Mega Drain':27,
        'Toxic':36,
        'Moonblast':45
    },
    '045':{
        'Absorb':1,
        'Growth':1,
        'Acid':1,
        'Poison Powder':1,
        'Solar Beam':1,
        'Petal Dance':54
    },
    '046':{
        'Scratch':1,
        'Sleep Powder':2,
        'Stun Spore':4,
        'Poison Powder':6,
        'Absorb':9,
        'Growth':12,
        'Fury Swipes':15,
        'Slash':19,
        'Leech Life':23,
        'Spore':27,
        'X-Scissor':31
    },
    '047':{
        'Scratch':1,
        'Screech':1,
        'Sleep Powder':1,
        'Stun Spore':1,
        'Poison Powder':1,
        'Absorb':1,
        'Growth':1,
        'Fury Swipes':1,
        'Slash':1,
        'Leech Life':1,
        'Spore':33,
        'X-Scissor':43
    },
    '048':{
        'Tackle':1,
        'Supersonic':8,
        'Confusion':12,
        'Poison Powder':14,
        'Stun Spore':16,
        'Psybeam':20,
        'Sleep Powder':24,
        'Leech Life':28,
        'Psychic':32
    },
    '049':{
        'Agility':1,
        'Supersonic':1,
        'Confusion':1,
        'Gust':1,
        'Screech':1,
        'Tackle':1,
        'Poison Powder':1,
        'Stun Spore':1,
        'Psybeam':1,
        'Sleep Powder':1,
        'Leech Life':1,
        'Psychic':37,
        'Bug Buzz':46,
        'Quiver Dance':55
    },
    '050':{
        'Scratch':1,
        'Sand Attack':4,
        'Growl':8,
        'Agility':12,
        'Fury Swipes':15,
        'Dig':18,
        'Slash':21,
        'Sucker Punch':25,
        'Earthquake':29,
        'Fissure':33
    },
    '051':{
        'Screech':1,
        'Tri Attack':1,
        'Scratch':1,
        'Sand Attack':1,
        'Growl':1,
        'Agility':1,
        'Fury Swipes':1,
        'Dig':1,
        'Slash':1,
        'Sucker Punch':1,
        'Earthquake':35,
        'Fissure':45
    },
    '052':{
        'Bite':1,
        'Fake Out':1,
        'Growl':1,
        'Scratch':1,
        'Fury Swipes':19,
        'Screech':23,
        'Slash':27,
        'Nasty Plot':31,
        'Play Rough':35
    },
    '053':{
        'Amnesia':1,
        'Bite':1,
        'Fake Out':1,
        'Growl':1,
        'Hypnosis':1,
        'Scratch':1,
        'Swift':1,
        'Fury Swipes':1,
        'Screech':1,
        'Slash':1,
        'Nasty Plot':37,
        'Play Rough':47
    },
    '054':{
        'Scratch':1,
        'Tail Whip':5,
        'Water Gun':9,
        'Confusion':14,
        'Fury Swipes':18,
        'Psybeam':27,
        'Screech':32,
        'Surf':36,
        'Amnesia':41,
        'Hydro Pump':45
    },
    '055':{
        'Confusion':1,
        'Scratch':1,
        'Tail Whip':1,
        'Water Gun':1,
        'Yawn':1,
        'Fury Swipes':1,
        'Psybeam':1,
        'Screech':1,
        'Surf':42,
        'Amnesia':53,
        'Hydro Pump':63
    },
    '056':{
        'Leer':1,
        'Scratch':1,
        'Karate Chop':13,
        'Fury Swipes':16,
        'U-Turn':29,
        'Screech':32,
        'Thrash':37,
        'Outrage':40
    },
    '057':{
        'Leer':1,
        'Scratch':1,
        'Karate Chop':1,
        'Fury Swipes':1,
        'U-Turn':33,
        'Screech':40,
        'Thrash':49,
        'Outrage':56
    },
    '058':{
        'Bite':1,
        'Ember':3,
        'Leer':7,
        'Take Down':14,
        'Flamethrower':17,
        'Agility':21,
        'Heat Wave':24,
        'Crunch':28,
        'Outrage':31,
        'Play Rough':35,
        'Flare Blitz':38
    },
    '059':{
        'Agility':1,
        'Bite':1,
        'Burn Up':1,
        'Crunch':1,
        'Ember':1,
        'Extreme Speed':1,
        'Fire Fang':1,
        'Flame Wheel':1,
        'Flamethrower':1,
        'Flare Blitz':1,
        'Howl':1,
        'Leer':1,
        'Play Rough':1,
        'Take Down':1,
        'Double-Edge':1
    },
    '060':{
        'Bubble':1,
        'Pound':4,
        'Hypnosis':8,
        'Water Gun':12,
        'Double Slap':16,
        'Bubble Beam':21,
        'Body Slam':31,
        'Hydro Pump':36
    },
    '061':{
        'Bubble':1,
        'Pound':1,
        'Hypnosis':1,
        'Water Gun':1,
        'Double Slap':1,
        'Bubble Beam':1,
        'Body Slam':39,
        'Hydro Pump':48
    },
    '062':{
        'Bubble':1,
        'Bulk Up':1,
        'Pound':1,
        'Hypnosis':1,
        'Water Gun':1,
        'Submission':1,
        'Superpower':57
    },
    '063':{
        'Confusion':1
    },
    '064':{
        'Confusion':1,
        'Flash':1,
        'Kinesis':1,
        'Psybeam':1,
        'Recover':39,
        'Psychic':45
    },
    '065':{
        'Barrier':1,
        'Calm Mind':1,
        'Confusion':1,
        'Flash':1,
        'Kinesis':1,
        'Psybeam':1,
        'Recover':39,
        'Psychic':45
    },
    '066':{
        'Leer':1,
        'Karate Chop':16,
        'Brick Break':21,
        'Submission':26,
        'Bulk Up':31,
        'Superpower':36
    },
    '067':{
        'Leer':1,
        'Karate Chop':1,
        'Brick Break':1,
        'Submission':1,
        'Bulk Up':37,
        'Superpower':48
    },
    '068':{
        'Strength':1,
        'Leer':1,
        'Karate Chop':1,
        'Brick Break':1,
        'Submission':1,
        'Bulk Up':37,
        'Superpower':48
    },
    '069':{
        'Vine Whip':1,
        'Growth':4,
        'Acid':12,
        'Sleep Powder':16,
        'Poison Powder':17,
        'Stun Spore':18,
        'Razor Leaf':22,
        'Poison Jab':26,
        'Slam':30
    },
    '070':{
        'Vine Whip':1,
        'Growth':1,
        'Acid':1,
        'Sleep Powder':1,
        'Poison Powder':1,
        'Stun Spore':1,
        'Razor Leaf':27,
        'Poison Jab':36,
        'Slam':45
    },
    '071':{
        'Vine Whip':1,
        'Growth':1,
        'Acid':1,
        'Sucker Punch':1,
        'Swords Dance':1,
        'Leech Life':1,
        'Power Whip':54
    },
    '072':{
        'Poison Sting':1,
        'Constrict':4,
        'Supersonic':9,
        'Acid':13,
        'Bubble Beam':18,
        'Surf':27,
        'Barrier':31,
        'Poison Jab':36,
        'Screech':40,
        'Hydro Pump':45
    },
    '073':{
        'Acid':1,
        'Constrict':1,
        'Poison Sting':1,
        'Supersonic':1,
        'Bubble Beam':1,
        'Surf':1,
        'Barrier':36,
        'Poison Jab':46,
        'Screech':55,
        'Hydro Pump':65
    },
    '074':{
        'Defence Curl':1,
        'Tackle':1,
        'Sand Attack':3,
        'Rock Throw':9,
        'Take Down':15,
        'Self-Destruct':19,
        'Rock Slide':23,
        'Earthquake':27,
        'Double-Edge':31,
        'Explosion':35
    },
    '075':{
        'Defence Curl':1,
        'Tackle':1,
        'Sand Attack':1,
        'Rock Throw':1,
        'Take Down':1,
        'Self-Destruct':1,
        'Rock Slide':1,
        'Earthquake':31,
        'Double-Edge':39,
        'Explosion':47
    },
    '076':{
        'Defence Curl':1,
        'Mega Punch':1,
        'Tackle':1,
        'Sand Attack':1,
        'Rock Throw':1,
        'Take Down':1,
        'Self-Destruct':1,
        'Rock Slide':1,
        'Earthquake':31,
        'Double-Edge':39,
        'Explosion':47
    },
    '077':{
        'Growl':1,
        'Tackle':1,
        'Tail Whip':1,
        'Ember':5,
        'Quick Attack':10,
        'Double Kick':15,
        'Stomp':20,
        'Fire Spin':26,
        'Agility':32,
        'Fire Blast':38,
        'Take Down':44,
        'Flare Blitz':51
    },
    '078':{
        'Fury Attack':1,
        'Growl':1,
        'Horn Drill':1,
        'Hypnosis':1,
        'Megahorn':1,
        'Poison Jab':1,
        'Tackle':1,
        'Tail Whip':1,
        'Ember':1,
        'Quick Attack':1,
        'Double Kick':1,
        'Stomp':1,
        'Fire Spin':1,
        'Agility':1,
        'Fire Blast':1,
        'Take Down':51,
        'Flare Blitz':65
    },
    '079':{
        'Tackle':1,
        'Yawn':1,
        'Growl':6,
        'Water Gun':12,
        'Confusion':18,
        'Rest':30,
        'Surf':36,
        'Psychic':42,
        'Amnesia':48
    },
    '080':{
        'Tackle':1,
        'Yawn':1,
        'Growl':1,
        'Stomp':1,
        'Water Gun':1,
        'Withdraw':1,
        'Confusion':1,
        'Rest':1,
        'Surf':1,
        'Psychic':49,
        'Amnesia':62
    },
    '081':{
        'Tackle':1,
        'Supersonic':1,
        'Thunder Shock':5,
        'Thunder Wave':10,
        'Sonic':15,
        'Thunderbolt':26,
        'Screech':32,
        'Flash Cannon':38,
        'Thunder':44
    },
    '082':{
        'Tackle':1,
        'Supersonic':1,
        'Thunder Shock':1,
        'Thunder Wave':1,
        'Tri Attack':1,
        'Sonic':15,
        'Thunderbolt':26,
        'Screech':36,
        'Flash Cannon':46,
        'Thunder':56
    },
    '083':{
        'Leer':1,
        'Peck':1,
        'Poison Jab':1,
        'Quick Attack':1,
        'Sand Attack':1,
        'Cut':9,
        'Razor Leaf':13,
        'Fury Attack':18,
        'Agility':22,
        'Slash':27,
        'Air Slash':31,
        'Swords Dance':36,
        'Sky Attack':40
    },
    '084':{
        'Peck':1,
        'Growl':1,
        'Quick Attack':5,
        'Fury Atack':16,
        'Agility':22,
        'Drill Peck':27,
        'Swords Dance':32,
        'Jump Kick':38,
        'Thrash':44
    },
    '085':{
        'Peck':1,
        'Growl':1,
        'Supersonic':1,
        'Quick Attack':1,
        'Tri Attack':1,
        'Fury Atack':1,
        'Agility':1,
        'Drill Peck':1,
        'Swords Dance':37,
        'Jump Kick':48,
        'Thrash':59
    },
    '086':{
        'Headbutt':1,
        'Growl':4,
        'Aqua Jet':12,
        'Ice Shard':16,
        'Rest':20,
        'Aurora Beam':26,
        'Waterfall':32,
        'Take Down':38,
        'Ice Beam':44,
        'Double-Edge':50
    },
    '087':{
        'Headbutt':1,
        'Horn Drill':1,
        'Growl':1,
        'Aqua Jet':1,
        'Ice Shard':1,
        'Rest':1,
        'Aurora Beam':1,
        'Waterfall':1,
        'Take Down':42,
        'Ice Beam':52,
        'Double-Edge':62
    },
    '088':{
        'Poison Gas':1,
        'Pound':1,
        'Harden':6,
        'Sludge':24,
        'Screech':30,
        'Toxic':36,
        'Acid Armor':42,
        'Sludge Bomb':48
    },
    '089':{
        'Poison Gas':1,
        'Pound':1,
        'Moonblast':1,
        'Harden':1,
        'Sludge':1,
        'Screech':1,
        'Toxic':1,
        'Acid Armor':48,
        'Sludge Bomb':60
    },
    '090':{
        'Tackle':1,
        'Water Gun':1,
        'Withdraw':4,
        'Leer':9,
        'Ice Shard':13,
        'Supersonic':18,
        'Aurora Beam':27,
        'Ice Beam':36,
        'Shell Smash':40,
        'Hydro Pump':45
    },
    '091':{
        'Icicle Crash':1,
        'Icicle Spear':1,
        'Iron Defence':1,
        'Tackle':1,
        'Water Gun':1,
        'Withdraw':1,
        'Leer':1,
        'Ice Shard':1,
        'Supersonic':1,
        'Aurora Beam':1,
        'Ice Beam':1,
        'Shell Smash':1,
        'Hydro Pump':1,
        'Razor Shell':1
    },
    '092':{
        'Hypnosis':1,
        'Lick':1,
        'Smog':1,
        'Confuse Ray':5,
        'Poison Gas':7,
        'Will-O-Wisp':14,
        'Sucker Punch':19,
        'Toxic':21,
        'Shadow Ball':26,
        'Dark Pulse':28
    },
    '093':{
        'Hypnosis':1,
        'Lick':1,
        'Smog':1,
        'Confuse Ray':1,
        'Poison Gas':1,
        'Will-O-Wisp':1,
        'Sucker Punch':1,
        'Toxic':1,
        'Shadow Ball':30,
        'Dark Pulse':36
    },
    '094':{
        'Hypnosis':1,
        'Lick':1,
        'Smog':1,
        'Confuse Ray':1,
        'Poison Gas':1,
        'Will-O-Wisp':1,
        'Sucker Punch':1,
        'Toxic':1,
        'Shadow Ball':30,
        'Dark Pulse':36
    }
}

tm = {
    '001': {}
}