compatible = {
    '001': {
        'Growl':1,
        'Tackle':1,
        'Vine Whip':5,
        'Poison Powder':14,
        'Sleep Powder':14,
        'Take Down':18,
        'Razor Leaf':23,
        'Growth':27,
        'Double-Edge':32
    },
    '002': {
        'Growl':1,
        'Tackle':1,
        'Vine Whip':1,
        'Poison Powder':1,
        'Sleep Powder':1,
        'Take Down':22,
        'Razor Leaf':31,
        'Growth':39,
        'Double-Edge':48,
        'Solar Beam':56
    },
    '003': {
        'Amnesia':1,
        'Growl':1,
        'Tackle':1,
        'Vine Whip':1,
        'Poison Powder':1,
        'Sleep Powder':1,
        'Petal Blizzard':1,
        'Petal Dance':1,
        'Power Whip':1,
        'Take Down':1,
        'Razor Leaf':1,
        'Growth':44,
        'Double-Edge':58,
        'Solar Beam':71
    },
    '004': {
        'Growl':1,
        'Scratch':1,
        'Smokescreen':9,
        'Ember':13,
        'Fury Swipes':18,
        'Slash':31,
        'Flamethrower':36
    },
    '005': {
        'Ember':1,
        'Growl':1,
        'Scratch':1,
        'Smokescreen':1,
        'Fury Swipes':20,
        'Slash':39,
        'Flamethrower':46
    },
    '006': {
        'Crunch':1,
        'Ember':1,
        'Growl':1,
        'Heat Wave':1,
        'Scratch':1,
        'Smokecreen':1,
        'Wing Attack':1,
        'Fury Swipes':1,
        'Fire Spin':1,
        'Slash':43,
        'Flamethrower':54,
        'Air Slash':62,
        'Flare Blitz':75
    },
    '007':{
        'Tackle':1,
        'Tail Whip':5,
        'Bubble':9,
        'Withdraw':14,
        'Water Gun':19,
        'Bite':23,
        'Bubble Beam':27,
        'Headbutt':36,
        'Hydro Pump':41,
        'Skull Bash':45
    },
    '008':{
        'Tackle':1,
        'Tail Whip':1,
        'Bubble':1,
        'Withdraw':1,
        'Water Gun':20,
        'Bite':27,
        'Bubble Beam':33,
        'Headbutt':46,
        'Hydro Pump':53,
        'Skull Bash':59
    },
    '009':{
        'Aqua Jet':1,
        'Tackle':1,
        'Fake Out':1,
        'Flash Cannon':1,
        'Tail Whip':1,
        'Bubble':1,
        'Withdraw':1,
        'Water Gun':1,
        'Bite':1,
        'Bubble Beam':1,
        'Headbutt':54,
        'Hydro Pump':65,
        'Skull Bash':75
    },
    '010':{
        'Tackle':1,
        'String Shot':1
    },
    '011':{
        'Harden':1
    },
    '012':{
        'Confusion':1,
        'Gust':1,
        'Poison Powder':13,
        'Sleep Powder':13,
        'Stun Spore':13,
        'Psybeam':16,
        'Supersonic':19,
        'Quiver Dance':22,
        'Air Slash':28,
        'Bug Buzz':31
    },
    '013':{
        'Poison Sting':1,
        'String Shot':1
    },
    '014':{
        'Harden':1
    },
    '015':{
        'Twineedle':1,
        'Peck':1,
        'Rage':13,
        'Fury Attack':16,
        'Poison Jab':22,
        'Agility':25,
        'Pin Missile':28,
        'Outrage':31
    },
    '016':{
        'Tackle':1,
        'Sand Attack':3,
        'Gust':5,
        'Quick Attack':11,
        'Wing Attack':15,
        'Roost':17,
        'Agility':23,
        'Air Slash':27,
        'Razor Wind':31
    },
    '017':{
        'Tackle':1,
        'Sand Attack':1,
        'Gust':1,
        'Quick Attack':11,
        'Wing Attack':1,
        'Roost':1,
        'Agility':31,
        'Air Slash':39,
        'Razor Wind':45
    },
    '018':{
        'Heat Wave':1,
        'Tackle':1,
        'Sand Attack':1,
        'Gust':1,
        'Quick Attack':1,
        'Sky Attack':1,
        'Wing Attack':1,
        'Roost':1,
        'Agility':1,
        'Air Slash':43,
        'Razor Wind':53
    },
    '019':{
        'Tackle':1,
        'Tail Whip':3,
        'Quick Attack':6,
        'Bite':12,
        'Crunch':18,
        'Hyper Fang':21,
        'Sucker Punch':24,
        'Double-Edge':27
    },
    '020':{
        'Tackle':1,
        'Tail Whip':1,
        'Quick Attack':1,
        'Fury Swipes':1,
        'Swords Dance':1,
        'Bite':1,
        'Crunch':1,
        'Hyper Fang':26,
        'Sucker Punch':34,
        'Double-Edge':42
    },
    '021':{
        'Peck':1,
        'Growl':3,
        'Leer':8,
        'Fury Attack':16,
        'Roost':24,
        'Agility':27,
        'Drill Peck':32
    },
    '022':{
        'Drill Run':1,
        'Growl':1,
        'Leer':1,
        'Peck':1,
        'Quick Attack':1,
        'Sky Attack':1,
        'Fury Attack':1,
        'Roost':29,
        'Agility':37,
        'Drill Peck':47
    },
    '023':{
        'Poison Sting':1,
        'Leer':4,
        'Acid':8,
        'Bite':12,
        'Glare':20,
        'Poison Jab':24,
        'Slam':28,
        'Screech':32,
        'Toxic':36
    },
    '024':{
        'Crunch':1,
        'Poison Sting':1,
        'Leer':1,
        'Acid':1,
        'Sucker Punch':1,
        'Bite':1,
        'Glare':1,
        'Poison Jab':28,
        'Slam':36,
        'Screech':44,
        'Toxic':52
    },
    '025':{
        'Growl':1,
        'Thunder Shock':1,
        'Tail Whip':3,
        'Quick Attack':6,
        'Double Kick':9,
        'Thunder Wave':15,
        'Thunderbolt':21,
        'Slam':24,
        'Agility':27,
        'Thunder':30
    },
    '026':{
        'Discharge':1,
        'Fake Out':1,
        'Growl':1,
        'Nuzzle':1,
        'Quick Attack':1,
        'Spark':1,
        'Tail Whip':1,
        'Thunder Wave':1,
        'Thunder Punch':1,
        'Thunder Shock':1,
        'Thunderbolt':1,
        'Thunder':1
    },
    '027':{
        'Defence Curl':1,
        'Scratch':1,
        'Poison Sting':4,
        'Sand Attack':8,
        'Swift':12,
        'Fury Swipes':16,
        'Dig':20,
        'Swords Dance':28,
        'Slash':32,
        'Earthquake':36
    },
    '028':{
        'Defence Curl':1,
        'Scratch':1,
        'Poison Sting':1,
        'Sand Attack':1,
        'Swift':1,
        'Fury Swipes':1,
        'Dig':1,
        'Swords Dance':36,
        'Slash':44,
        'Earthquake':52
    },
    '029':{
        'Growl':1,
        'Scratch':1,
        'Tail Whip':3,
        'Poison Sting':6,
        'Double Kick':9,
        'Bite':12,
        'Toxic':18,
        'Fury Swipes':21,
        'Crunch':24
    },
    '030':{
        'Growl':1,
        'Scratch':1,
        'Tail Whip':1,
        'Poison Sting':1,
        'Double Kick':1,
        'Bite':1,
        'Toxic':23,
        'Fury Swipes':31,
        'Crunch':39
    },
    '031':{
        'Body Slam':1,
        'Growl':1,
        'Scratch':1,
        'Poison Sting':1,
        'Supersonic':1,
        'Tail Whip':1,
        'Superpower':55
    },
    '032':{
        'Leer':1,
        'Peck':1,
        'Poison Sting':3,
        'Double Kick':6,
        'Horn Attack':12,
        'Toxic':18,
        'Fury Attack':21,
        'Poison Jab':24,
        'Horn Drill':27
    },
    '033':{
        'Leer':1,
        'Peck':1,
        'Poison Sting':1,
        'Double Kick':1,
        'Horn Attack':1,
        'Toxic':23,
        'Fury Attack':31,
        'Poison Jab':39,
        'Horn Drill':47,
    },
    '034':{
        'Leer':1,
        'Peck':1,
        'Poison Sting':1,
        'Supersonic':1,
        'Thrash':1,
        'Megahorn':55
    },
    '035':{
        'Growl':1,
        'Pound':1,
        'Defence Curl':4,
        'Sing':6,
        'Double Slap':12,
        'Amnesia':16,
        'Body Slam':24,
        'Moonblast':28
    },
    '036':{
        'Growl':1,
        'Pound':1,
        'Defence Curl':1,
        'Sing':1,
        'Charm':1,
        'Cosmic Power':1,
        'Meteor Mash':1,
        'Moonblast':1,
        'Splash':1,
        'Stored Power':1,
        'Sweet Kiss':1
    },
    '037':{
        'Tackle':1,
        'Tail Whip':3,
        'Ember':7,
        'Quick Attack':10,
        'Confuse Ray':14,
        'Will-O-Wisp':17,
        'Flamethrower':24,
        'Fire Blast':31
    },
    '038':{
        'Confuse Ray':1,
        'Ember':1,
        'Hypnosis':1,
        'Nasty Plot':1,
        'Quick Attack':1,
        'Tackle':1,
        'Tail Whip':1,
        'Fire Blast':1,
        'Flamethrower':1,
        'Incinerate':1,
        'Inferno':1,
        'Will-O-Wisp':1
    },
    '039':{
        'Sing':1,
        'Pound':4,
        'Defence Curl':6,
        'Double Slap':12,
        'Rest':18,
        'Body Slam':22,
        'Double-Edge':28
    },
    '040':{
        'Body Slam':1,
        'Charm':1,
        'Covet':1,
        'Defence Curl':1,
        'Disarming Voice':1,
        'Double-Edge':1,
        'Echoed Voice':1,
        'Hyper Voice':1,
        'Play Rough':1,
        'Pound':1,
        'Rest':1,
        'Round':1,
        'Sing':1,
        'Sweet Kiss':1
    },
    '041':{
        'Absorb':1,
        'Supersonic':1,
        'Wing Attack':4,
        'Bite':9,
        'Swift':12,
        'Confuse Ray':17,
        'Leech Life':25,
        'Toxic':28,
        'Air Slash':33
    },
    '042':{
        'Absorb':1,
        'Crunch':1,
        'Quick Attack':1,
        'Supersonic':1,
        'Wing Attack':1,
        'Bite':1,
        'Swift':1,
        'Confuse Ray':1,
        'Leech Life':31,
        'Toxic':40,
        'Air Slash':51
    },
    '043':{
        'Absorb':1,
        'Growth':4,
        'Acid':8,
        'Poison Powder':12,
        'Stun Spore':13,
        'Sleep Powder':14,
        'Razor Leaf':18,
        'Mega Drain':22,
        'Toxic':26,
        'Moonblast':30
    },
    '044':{
        'Absorb':1,
        'Growth':1,
        'Acid':1,
        'Poison Powder':1,
        'Stun Spore':1,
        'Sleep Powder':1,
        'Razor Leaf':1,
        'Mega Drain':27,
        'Toxic':36,
        'Moonblast':45
    },
    '045':{
        'Absorb':1,
        'Growth':1,
        'Acid':1,
        'Poison Powder':1,
        'Solar Beam':1,
        'Petal Dance':54
    },
    '046':{
        'Scratch':1,
        'Sleep Powder':2,
        'Stun Spore':4,
        'Poison Powder':6,
        'Absorb':9,
        'Growth':12,
        'Fury Swipes':15,
        'Slash':19,
        'Leech Life':23,
        'Spore':27,
        'X-Scissor':31
    },
    '047':{
        'Scratch':1,
        'Screech':1,
        'Sleep Powder':1,
        'Stun Spore':1,
        'Poison Powder':1,
        'Absorb':1,
        'Growth':1,
        'Fury Swipes':1,
        'Slash':1,
        'Leech Life':1,
        'Spore':33,
        'X-Scissor':43
    },
    '048':{
        'Tackle':1,
        'Supersonic':8,
        'Confusion':12,
        'Poison Powder':14,
        'Stun Spore':16,
        'Psybeam':20,
        'Sleep Powder':24,
        'Leech Life':28,
        'Psychic':32
    },
    '049':{
        'Agility':1,
        'Supersonic':1,
        'Confusion':1,
        'Gust':1,
        'Screech':1,
        'Tackle':1,
        'Poison Powder':1,
        'Stun Spore':1,
        'Psybeam':1,
        'Sleep Powder':1,
        'Leech Life':1,
        'Psychic':37,
        'Bug Buzz':46,
        'Quiver Dance':55
    },
    '050':{
        'Scratch':1,
        'Sand Attack':4,
        'Growl':8,
        'Agility':12,
        'Fury Swipes':15,
        'Dig':18,
        'Slash':21,
        'Sucker Punch':25,
        'Earthquake':29,
        'Fissure':33
    },
    '051':{
        'Screech':1,
        'Tri Attack':1,
        'Scratch':1,
        'Sand Attack':1,
        'Growl':1,
        'Agility':1,
        'Fury Swipes':1,
        'Dig':1,
        'Slash':1,
        'Sucker Punch':1,
        'Earthquake':35,
        'Fissure':45
    },
    '052':{
        'Bite':1,
        'Fake Out':1,
        'Growl':1,
        'Scratch':1,
        'Fury Swipes':19,
        'Screech':23,
        'Slash':27,
        'Nasty Plot':31,
        'Play Rough':35
    },
    '053':{
        'Amnesia':1,
        'Bite':1,
        'Fake Out':1,
        'Growl':1,
        'Hypnosis':1,
        'Scratch':1,
        'Swift':1,
        'Fury Swipes':1,
        'Screech':1,
        'Slash':1,
        'Nasty Plot':37,
        'Play Rough':47
    },
    '054':{
        'Scratch':1,
        'Tail Whip':5,
        'Water Gun':9,
        'Confusion':14,
        'Fury Swipes':18,
        'Psybeam':27,
        'Screech':32,
        'Surf':36,
        'Amnesia':41,
        'Hydro Pump':45
    },
    '055':{
        'Confusion':1,
        'Scratch':1,
        'Tail Whip':1,
        'Water Gun':1,
        'Yawn':1,
        'Fury Swipes':1,
        'Psybeam':1,
        'Screech':1,
        'Surf':42,
        'Amnesia':53,
        'Hydro Pump':63
    },
    '056':{
        'Leer':1,
        'Scratch':1,
        'Karate Chop':13,
        'Fury Swipes':16,
        'U-Turn':29,
        'Screech':32,
        'Thrash':37,
        'Outrage':40
    },
    '057':{
        'Leer':1,
        'Scratch':1,
        'Karate Chop':1,
        'Fury Swipes':1,
        'U-Turn':33,
        'Screech':40,
        'Thrash':49,
        'Outrage':56
    },
    '058':{
        'Bite':1,
        'Ember':3,
        'Leer':7,
        'Take Down':14,
        'Flamethrower':17,
        'Agility':21,
        'Heat Wave':24,
        'Crunch':28,
        'Outrage':31,
        'Play Rough':35,
        'Flare Blitz':38
    },
    '059':{
        'Agility':1,
        'Bite':1,
        'Burn Up':1,
        'Crunch':1,
        'Ember':1,
        'Extreme Speed':1,
        'Fire Fang':1,
        'Flame Wheel':1,
        'Flamethrower':1,
        'Flare Blitz':1,
        'Howl':1,
        'Leer':1,
        'Play Rough':1,
        'Take Down':1,
        'Double-Edge':1
    },
    '060':{
        'Bubble':1,
        'Pound':4,
        'Hypnosis':8,
        'Water Gun':12,
        'Double Slap':16,
        'Bubble Beam':21,
        'Body Slam':31,
        'Hydro Pump':36
    },
    '061':{
        'Bubble':1,
        'Pound':1,
        'Hypnosis':1,
        'Water Gun':1,
        'Double Slap':1,
        'Bubble Beam':1,
        'Body Slam':39,
        'Hydro Pump':48
    },
    '062':{
        'Bubble':1,
        'Bulk Up':1,
        'Pound':1,
        'Hypnosis':1,
        'Water Gun':1,
        'Submission':1,
        'Superpower':57
    },
    '063':{
        'Confusion':1
    },
    '064':{
        'Confusion':1,
        'Flash':1,
        'Kinesis':1,
        'Psybeam':1,
        'Recover':39,
        'Psychic':45
    },
    '065':{
        'Barrier':1,
        'Calm Mind':1,
        'Confusion':1,
        'Flash':1,
        'Kinesis':1,
        'Psybeam':1,
        'Recover':39,
        'Psychic':45
    },
    '066':{
        'Leer':1,
        'Karate Chop':16,
        'Brick Break':21,
        'Submission':26,
        'Bulk Up':31,
        'Superpower':36
    },
    '067':{
        'Leer':1,
        'Karate Chop':1,
        'Brick Break':1,
        'Submission':1,
        'Bulk Up':37,
        'Superpower':48
    },
    '068':{
        'Strength':1,
        'Leer':1,
        'Karate Chop':1,
        'Brick Break':1,
        'Submission':1,
        'Bulk Up':37,
        'Superpower':48
    },
    '069':{
        'Vine Whip':1,
        'Growth':4,
        'Acid':12,
        'Sleep Powder':16,
        'Poison Powder':17,
        'Stun Spore':18,
        'Razor Leaf':22,
        'Poison Jab':26,
        'Slam':30
    },
    '070':{
        'Vine Whip':1,
        'Growth':1,
        'Acid':1,
        'Sleep Powder':1,
        'Poison Powder':1,
        'Stun Spore':1,
        'Razor Leaf':27,
        'Poison Jab':36,
        'Slam':45
    },
    '071':{
        'Vine Whip':1,
        'Growth':1,
        'Acid':1,
        'Sucker Punch':1,
        'Swords Dance':1,
        'Leech Life':1,
        'Power Whip':54
    },
    '072':{
        'Poison Sting':1,
        'Constrict':4,
        'Supersonic':9,
        'Acid':13,
        'Bubble Beam':18,
        'Surf':27,
        'Barrier':31,
        'Poison Jab':36,
        'Screech':40,
        'Hydro Pump':45
    },
    '073':{
        'Acid':1,
        'Constrict':1,
        'Poison Sting':1,
        'Supersonic':1,
        'Bubble Beam':1,
        'Surf':1,
        'Barrier':36,
        'Poison Jab':46,
        'Screech':55,
        'Hydro Pump':65
    },
    '074':{
        'Defence Curl':1,
        'Tackle':1,
        'Sand Attack':3,
        'Rock Throw':9,
        'Take Down':15,
        'Self-Destruct':19,
        'Rock Slide':23,
        'Earthquake':27,
        'Double-Edge':31,
        'Explosion':35
    },
    '075':{
        'Defence Curl':1,
        'Tackle':1,
        'Sand Attack':1,
        'Rock Throw':1,
        'Take Down':1,
        'Self-Destruct':1,
        'Rock Slide':1,
        'Earthquake':31,
        'Double-Edge':39,
        'Explosion':47
    },
    '076':{
        'Defence Curl':1,
        'Mega Punch':1,
        'Tackle':1,
        'Sand Attack':1,
        'Rock Throw':1,
        'Take Down':1,
        'Self-Destruct':1,
        'Rock Slide':1,
        'Earthquake':31,
        'Double-Edge':39,
        'Explosion':47
    },
    '077':{
        'Growl':1,
        'Tackle':1,
        'Tail Whip':1,
        'Ember':5,
        'Quick Attack':10,
        'Double Kick':15,
        'Stomp':20,
        'Fire Spin':26,
        'Agility':32,
        'Fire Blast':38,
        'Take Down':44,
        'Flare Blitz':51
    },
    '078':{
        'Fury Attack':1,
        'Growl':1,
        'Horn Drill':1,
        'Hypnosis':1,
        'Megahorn':1,
        'Poison Jab':1,
        'Tackle':1,
        'Tail Whip':1,
        'Ember':1,
        'Quick Attack':1,
        'Double Kick':1,
        'Stomp':1,
        'Fire Spin':1,
        'Agility':1,
        'Fire Blast':1,
        'Take Down':51,
        'Flare Blitz':65
    },
    '079':{
        'Tackle':1,
        'Yawn':1,
        'Growl':6,
        'Water Gun':12,
        'Confusion':18,
        'Rest':30,
        'Surf':36,
        'Psychic':42,
        'Amnesia':48
    },
    '080':{
        'Tackle':1,
        'Yawn':1,
        'Growl':1,
        'Stomp':1,
        'Water Gun':1,
        'Withdraw':1,
        'Confusion':1,
        'Rest':1,
        'Surf':1,
        'Psychic':49,
        'Amnesia':62
    },
    '081':{
        'Tackle':1,
        'Supersonic':1,
        'Thunder Shock':5,
        'Thunder Wave':10,
        'Sonic':15,
        'Thunderbolt':26,
        'Screech':32,
        'Flash Cannon':38,
        'Thunder':44
    },
    '082':{
        'Tackle':1,
        'Supersonic':1,
        'Thunder Shock':1,
        'Thunder Wave':1,
        'Tri Attack':1,
        'Sonic':15,
        'Thunderbolt':26,
        'Screech':36,
        'Flash Cannon':46,
        'Thunder':56
    },
    '083':{
        'Leer':1,
        'Peck':1,
        'Poison Jab':1,
        'Quick Attack':1,
        'Sand Attack':1,
        'Cut':9,
        'Razor Leaf':13,
        'Fury Attack':18,
        'Agility':22,
        'Slash':27,
        'Air Slash':31,
        'Swords Dance':36,
        'Sky Attack':40
    },
    '084':{
        'Peck':1,
        'Growl':1,
        'Quick Attack':5,
        'Fury Atack':16,
        'Agility':22,
        'Drill Peck':27,
        'Swords Dance':32,
        'Jump Kick':38,
        'Thrash':44
    },
    '085':{
        'Peck':1,
        'Growl':1,
        'Supersonic':1,
        'Quick Attack':1,
        'Tri Attack':1,
        'Fury Atack':1,
        'Agility':1,
        'Drill Peck':1,
        'Swords Dance':37,
        'Jump Kick':48,
        'Thrash':59
    },
    '086':{
        'Headbutt':1,
        'Growl':4,
        'Aqua Jet':12,
        'Ice Shard':16,
        'Rest':20,
        'Aurora Beam':26,
        'Waterfall':32,
        'Take Down':38,
        'Ice Beam':44,
        'Double-Edge':50
    },
    '087':{
        'Headbutt':1,
        'Horn Drill':1,
        'Growl':1,
        'Aqua Jet':1,
        'Ice Shard':1,
        'Rest':1,
        'Aurora Beam':1,
        'Waterfall':1,
        'Take Down':42,
        'Ice Beam':52,
        'Double-Edge':62
    },
    '088':{
        'Poison Gas':1,
        'Pound':1,
        'Harden':6,
        'Sludge':24,
        'Screech':30,
        'Toxic':36,
        'Acid Armor':42,
        'Sludge Bomb':48
    },
    '089':{
        'Poison Gas':1,
        'Pound':1,
        'Moonblast':1,
        'Harden':1,
        'Sludge':1,
        'Screech':1,
        'Toxic':1,
        'Acid Armor':48,
        'Sludge Bomb':60
    },
    '090':{
        'Tackle':1,
        'Water Gun':1,
        'Withdraw':4,
        'Leer':9,
        'Ice Shard':13,
        'Supersonic':18,
        'Aurora Beam':27,
        'Ice Beam':36,
        'Shell Smash':40,
        'Hydro Pump':45
    },
    '091':{
        'Icicle Crash':1,
        'Icicle Spear':1,
        'Iron Defence':1,
        'Tackle':1,
        'Water Gun':1,
        'Withdraw':1,
        'Leer':1,
        'Ice Shard':1,
        'Supersonic':1,
        'Aurora Beam':1,
        'Ice Beam':1,
        'Shell Smash':1,
        'Hydro Pump':1,
        'Razor Shell':1
    },
    '092':{
        'Hypnosis':1,
        'Lick':1,
        'Smog':1,
        'Confuse Ray':5,
        'Poison Gas':7,
        'Will-O-Wisp':14,
        'Sucker Punch':19,
        'Toxic':21,
        'Shadow Ball':26,
        'Dark Pulse':28
    },
    '093':{
        'Hypnosis':1,
        'Lick':1,
        'Smog':1,
        'Confuse Ray':1,
        'Poison Gas':1,
        'Will-O-Wisp':1,
        'Sucker Punch':1,
        'Toxic':1,
        'Shadow Ball':30,
        'Dark Pulse':36
    },
    '094':{
        'Hypnosis':1,
        'Lick':1,
        'Smog':1,
        'Confuse Ray':1,
        'Poison Gas':1,
        'Will-O-Wisp':1,
        'Sucker Punch':1,
        'Toxic':1,
        'Shadow Ball':30,
        'Dark Pulse':36
    },
    '095':{
        'Harden':1,
        'Rock Throw':1,
        'Tackle':1,
        'Screech':15,
        'Dig':20,
        'Slam':25,
        'Rock Slide':30,
        'Earthquake':35,
        'Iron Tail':40,
        'Double-Edge':45
    },
    '096':{
        'Hypnosis':1,
        'Pound':1,
        'Confusion':9,
        'Poison Gas':13,
        'Meditate':18,
        'Psybeam':22,
        'Headbutt':27,
        'Psychic':31,
        'Nasty Plot':36
    },
    '097':{
        'Barrier':1,
        'Hypnosis':1,
        'Pound':1,
        'Confusion':9,
        'Poison Gas':13,
        'Meditate':18,
        'Psybeam':22,
        'Headbutt':27,
        'Psychic':36,
        'Nasty Plot':46
    },
    '098':{
        'Bubble':1,
        'Vise Grip':5,
        'Leer':9,
        'Harden':14,
        'Bubble Beam':18,
        'Stomp':23,
        'Protect':27,
        'Slam':32,
        'Crabhammer':36,
        'Guillotine':41
    },
    '099':{
        'Agility':1,
        'Amnesia':1,
        'Bubble':1,
        'Vise Grip':5,
        'Leer':9,
        'Harden':14,
        'Bubble Beam':18,
        'Stomp':23,
        'Protect':27,
        'Slam':37,
        'Crabhammer':46,
        'Guillotine':56
    },
    '100':{
        'Tackle':1,
        'Light Screen':3,
        'Sonic Boom':6,
        'Thunder Shock':9,
        'Swift':14,
        'Self-Destruct':19,
        'Screech':24,
        'Thunderbolt':31,
        'Explosion':45
    },
    '101':{
        'Tackle':1,
        'Light Screen':1,
        'Sonic Boom':1,
        'Thunder Shock':1,
        'Swift':1,
        'Self-Destruct':1,
        'Screech':1,
        'Thunderbolt':36,
        'Explosion':60
    },
    '102':{
        'Barrage':1,
        'Hypnosis':7,
        'Confusion':14,
        'Stun Spore':16,
        'Poison Powder':18,
        'Sleep Powder':20,
        'Psybeam':27,
        'Solar Beam':48
    },
    '103':{
        'Barrage':1,
        'Hypnosis':1,
        'Confusion':1,
        'Stun Spore':1,
        'Power Whip':1,
        'Stomp':1,
        'Egg Bomb':1
    },
    '104':{
        'Growl':1,
        'Tail Whip':2,
        'Leer':6,
        'Bone Club':12,
        'Headbutt':14,
        'Bone Rush':18,
        'Bonemerang':26,
        'Thrash':30,
        'Double-Edge':36
    },
    '105':{
        'Growl':1,
        'Screech':1,
        'Swords Dance':1,
        'Tail Whip':1,
        'Leer':1,
        'Bone Club':1,
        'Headbutt':1,
        'Bone Rush':1,
        'Bonemerang':1,
        'Thrash':36,
        'Double-Edge':48
    },
    '106':{
        'Rolling Kick':1,
        'Meditate':5,
        'Double Kick':10,
        'Brick Break':20,
        'Facade':25,
        'Jump Kick':30,
        'Mega Kick':40,
        'High Jump Kick':45
    },
    '107':{
        'Comet Punch':1,
        'Agility':5,
        'Bullet Punch':10,
        'Swift':20,
        'Dizzy Punch':25,
        'Fire Punch':30,
        'Ice Punch':30,
        'Thunder Punch':30,
        'Mega Punch':40,
        'Close Combat':45
    },
    '108':{
        'Lick':1,
        'Acid':10,
        'Stomp':15,
        'Slam':30,
        'Screech':35,
        'Thrash':40,
        'Power Whip':45
    },
    '109':{
        'Poison Gas':1,
        'Tackle':1,
        'Smog':6,
        'Clear Smog':12,
        'Sludge':18,
        'Self-Destruct':24,
        'Toxic':30,
        'Sludge Bomb':42,
        'Explosion':48
    },
    '110':{
        'Psybeam':1,
        'Screech':1,
        'Poison Gas':1,
        'Tackle':1,
        'Smog':1,
        'Clear Smog':1,
        'Sludge':1,
        'Self-Destruct':1,
        'Toxic':30,
        'Sludge Bomb':50,
        'Explosion':60
    },
    '111':{
        'Horn Attack':1,
        'Sand Attack':1,
        'Tackle':1,
        'Fury Attack':7,
        'Stomp':12,
        'Rock Throw':19,
        'Drill Run':24,
        'Take Down':31,
        'Megahorn':36,
        'Rock Slide':43,
        'Earthquake':48,
        'Horn Drill':55
    },
    '112':{
        'Crunch':1,
        'Horn Attack':1,
        'Sand Attack':1,
        'Tackle':1,
        'Fury Attack':1,
        'Stomp':1,
        'Rock Throw':1,
        'Drill Run':1,
        'Take Down':1,
        'Megahorn':1,
        'Rock Slide':48,
        'Earthquake':54,
        'Horn Drill':67
    },
    '113':{
        'Growl':1,
        'Pound':1,
        'Defence Curl':4,
        'Tail Whip':8,
        'Double Slap':12,
        'Soft-Boiled':16,
        'Take Down':25,
        'Sing':30,
        'Egg Bomb':35,
        'Double-Edge':45
    },
    '114':{
        'Absorb':1,
        'Constrict':1,
        'Sleep Powder':5,
        'Confusion':10,
        'Vine Whip':15,
        'Poison Powder':17,
        'Growth':27,
        'Stun Spore':29,
        'Mega Drain':34,
        'Slam':44,
        'Amnesia':49,
        'Power Whip':54
    },
    '115':{
        'Comet Punch':1,
        'Leer':1,
        'Tail Whip':11,
        'Bite':17,
        'Mega Punch':28,
        'Dizzy Punch':33,
        'Crunch':39,
        'Outrage':44,
        'Sucker Punch':50
    },
    '116':{
        'Bubble':1,
        'Smokescreen':6,
        'Water Gun':9,
        'Leer':15,
        'Bubble Beam':18,
        'Waterfall':27,
        'Agility':33,
        'Dragon Pulse':36,
        'Hydro Pump':42
    },
    '117':{
        'Bubble':1,
        'Clear Smog':1,
        'Smokescreen':1,
        'Water Gun':1,
        'Leer':1,
        'Bubble Beam':1,
        'Waterfall':1,
        'Agility':36,
        'Dragon Pulse':42,
        'Hydro Pump':51
    },
    '118':{
        'Peck':1,
        'Tail Whip':1,
        'Supersonic':4,
        'Quick Attack':10,
        'Horn Attack':14,
        'Fury Attack':20,
        'Waterfall':24,
        'Agility':30,
        'Horn Drill':34,
        'Megahorn':40
    },
    '119':{
        'Psybeam':1,
        'Skull Bash':1,
        'Peck':1,
        'Tail Whip':1,
        'Supersonic':1,
        'Quick Attack':1,
        'Horn Attack':1,
        'Fury Attack':1,
        'Waterfall':1,
        'Agility':1,
        'Horn Drill':39,
        'Megahorn':50
    },
    '120':{
        'Harden':1,
        'Tackle':1,
        'Water Gun':9,
        'Swift':13,
        'Confuse Ray':22,
        'Bubble Beam':27,
        'Psychic':36,
        'Hydro Pump':45
    },
    '121':{
        'Brine':1,
        'Cosmic Power':1,
        'Harden':1,
        'Tackle':1,
        'Water Gun':1,
        'Swift':1,
        'Confuse Ray':1,
        'Bubble Beam':1,
        'Psychic':1,
        'Hydro Pump':1,
        'Power Gem':1,
        'Rapid Spin':1,
        'Psybeam':1,
        'Surf':1
    },
    '122':{
        'Barrier':1,
        'Confusion':1,
        'Pound':1,
        'Meditate':6,
        'Double Slap':10,
        'Psywave':20,
        'Psybeam':30,
        'Psychic':46
    },
    '123':{
        'Leer':1,
        'Quick Attack':1,
        'Wing Attack':16,
        'Agility':20,
        'Slash':26,
        'Razor Wind':32,
        'Air Slash':38,
        'Swords Dance':44,
        'X-Scissor':50
    },
    '124':{
        'Pound':1,
        'Lick':6,
        'Confusion':12,
        'Screech':18,
        'Double Slap':22,
        'Ice Punch':26,
        'Body Slam':30,
        'Lovely Kiss':35,
        'Psychic':40,
        'Blizzard':45
    },
    '125':{
        'Leer':1,
        'Thunder Shock':1,
        'Quick Attack':6,
        'Thunder Wave':11,
        'Swift':17,
        'Thunder Punch':33,
        'Screech':39,
        'Thunderbolt':44,
        'Thunder':50
    },
    '126':{
        'Ember':1,
        'Leer':1,
        'Smog':6,
        'Smokescreen':17,
        'Fire Spin':28,
        'Fire Punch':33,
        'Confuse Ray':39,
        'Flamethrower':44,
        'Fire Blast':50
    },
    '127':{
        'Vise Grip':1,
        'Harden':12,
        'Brick Break':16,
        'X-Scissor':20,
        'Submission':26,
        'Swords Dance':32,
        'Thrash':38,
        'Superpower':44,
        'Guillotine':50
    },
    '128':{
        'Tackle':1,
        'Tail Whip':6,
        'Horn Attack':18,
        'Leer':24,
        'Rest':30,
        'Take Down':34,
        'Thrash':42,
        'Double-Edge':46,
        'Outrage':50
    },
    '129':{
        'Splash':1,
        'Tackle':15
    },
    '130':{
        'Bite':1,
        'Leer':1,
        'Thrash':1,
        'Dragon Tail':26,
        'Waterfall':31,
        'Crunch':36,
        'Outrage':41,
        'Hydro Pump':46,
        'Hyper Beam':51
    },
    '131':{
        'Sing':1,
        'Water Gun':1,
        'Growl':6,
        'Ice Shard':19,
        'Confuse Ray':26,
        'Body Slam':32,
        'Ice Beam':39,
        'Surf':45,
        'Dragon Pulse':52,
        'Blizzard':58,
        'Hydro Pump':65
    },
    '132':{
        'Tackle':1,
        'Scratch':1,
        'Ember':1,
        'Water Gun':1,
        'Vine Whip':1
    },
    '133':{
        'Growl':1,
        'Tackle':1,
        'Tail Whip':3,
        'Quick Attack':6,
        'Double Kick':10,
        'Sand Attack':14,
        'Bite':17,
        'Swift':21,
        'Take Down':24,
        'Double-Edge':28
    },
    '134':{
        'Growl':1,
        'Tackle':1,
        'Water Gun':1,
        'Yawn':1,
        'Tail Whip':3,
        'Quick Attack':6,
        'Double Kick':10,
        'Sand Attack':14,
        'Aurora Beam':17,
        'Acid Armor':24,
        'Hydro Pump':31
    },
    '135':{
        'Growl':1,
        'Tackle':1,
        'Ember':1,
        'Yawn':1,
        'Tail Whip':3,
        'Quick Attack':6,
        'Double Kick':10,
        'Sand Attack':14,
        'Pin Missile':17,
        'Thunder Wave':21,
        'Agility':24,
        'Thunder':31
    },
    '136':{
        'Growl':1,
        'Tackle':1,
        'Ember':1,
        'Yawn':1,
        'Tail Whip':3,
        'Quick Attack':6,
        'Double Kick':10,
        'Sand Attack':14,
        'Smog':21,
        'Flare Blitz':31
    },
    '137':{
        'Tackle':1,
        'Sharpen':4,
        'Psybeam':9,
        'Agility':13,
        'Barrier':18,
        'Tri Attack':22,
        'Thunder Wave':27,
        'Recover':36,
        'Hyper Beam':40
    },
    '138':{
        'Constrict':1,
        'Withdraw':4,
        'Leer':11,
        'Water Gun':15,
        'Bite':22,
        'Rock Throw':26,
        'Rock Slide':37,
        'Hydro Pump':44,
        'Shell Smash':48
    },
    '139':{
        'Constrict':1,
        'Spike Cannon':1,
        'Supersonic':1,
        'Withdraw':1,
        'Leer':1,
        'Water Gun':1,
        'Bite':1,
        'Rock Throw':1,
        'Rock Slide':1,
        'Hydro Pump':50,
        'Shell Smash':60
    },
    '140':{
        'Scratch':1,
        'Harden':6,
        'Leer':12,
        'Absorb':18,
        'Aqua Jet':24,
        'Rock Throw':30,
        'Sand Attack':36,
        'Rock Slide':42,
        'Leech Life':48
    },
    '141':{
        'Scratch':1,
        'Confuse Ray':1,
        'Screech':1,
        'Slash':1,
        'Harden':1,
        'Leer':1,
        'Absorb':1,
        'Aqua Jet':1,
        'Rock Throw':1,
        'Sand Attack':1,
        'Rock Slide':45,
        'Leech Life':54,
        'Swords Dance':63
    },
    '142':{
        'Bite':1,
        'Wing Attack':1,
        'Roar':7,
        'Supersonic':14,
        'Rock Throw':21,
        'Agility':28,
        'Crunch':35,
        'Rock Slide':42,
        'Fly':49,
        'Take Down':56,
        'Hyper Beam':63
    },
    '143':{
        'Tackle':1,
        'Defence Curl':6,
        'Yawn':13,
        'Lick':19,
        'Headbutt':26,
        'Rest':32,
        'Screech':39,
        'Amnesia':45,
        'Body Slam':52,
        'Crunch':58,
        'Superpower':65
    },
    '144':{
        'Gust':1,
        'Ice Shard':1,
        'Leer':16,
        'Ice Beam':32,
        'Agility':40,
        'Roost':56,
        'Blizzard':64,
        'Sky Attack':72
    },
    '145':{
        'Peck':1,
        'Thunder Shock':1,
        'Thunder Wave':8,
        'Leer':16,
        'Drill Peck':24,
        'Thunderbolt':32,
        'Agility':40,
        'Roost':56,
        'Thunder':64,
        'Sky Attack':72
    },
    '146':{
        'Wing Attack':1,
        'Ember':1,
        'Leer':16,
        'Air Slash':24,
        'Flamethrower':32,
        'Agility':40,
        'Heat Wave':48,
        'Roost':56,
        'Solar Beam':64,
        'Sky Attack':72
    },
    '147':{
        'Leer':1,
        'Thunder Wave':7,
        'Agility':21,
        'Dragon Tail':28,
        'Slam':35,
        'Outrage':42,
        'Hyper Beam':49
    },
    '148':{
        'Leer':1,
        'Thunder Wave':1,
        'Agility':1,
        'Dragon Tail':1,
        'Slam':40,
        'Outrage':52,
        'Hyper Beam':64
    },
    '149':{
        'Aqua Jet':1,
        'Fire Punch':1,
        'Thunder Punch':1,
        'Wing Attack':1,
        'Leer':1,
        'Thunder Wave':1,
        'Agility':1,
        'Dragon Tail':1,
        'Slam':1,
        'Outrage':1,
        'Hyper Beam':70,
        'Roost':88
    },
    '150':{
        'Confusion':1,
        'Life Dew':1,
        'Swift':1,
        'Ancient Power':8,
        'Psycho Cut':16,
        'Amnesia':32,
        'Aura Sphere':40,
        'Psychic':48,
        'Psystrike':72,
        'Recover':80,
        'Future Sight':88
    },
    '151':{
        'Confusion':1,
        'Pound':1,
        'Swift':11,
        'Amnesia':22,
        'Psywave':33,
        'Barrier':44,
        'Mega Punch':55,
        'Psychic':77,
        'Nasty Plot':88
    },
    '152':{
        'Growl':1,
        'Tackle':1,
        'Razor Leaf':6,
        'Poison Powder':9,
        'Magical Leaf':20,
        'Body Slam':34,
        'Solar Beam':45
    },
    '153':{
        'Growl':1,
        'Tackle':1,
        'Razor Leaf':1,
        'Poison Powder':1,
        'Magical Leaf':22,
        'Body Slam':40,
        'Solar Beam':54
    },
    '154':{
        'Growl':1,
        'Petal Dance':1,
        'Tackle':1,
        'Razor Leaf':1,
        'Poison Powder':1,
        'Magical Leaf':1,
        'Body Slam':46,
        'Solar Beam':66,
        'Petal Blizzard':70
    },
    '155':{
        'Leer':1,
        'Tackle':1,
        'Smokescreen':6,
        'Ember':10,
        'Quick Attack':13,
        'Flame Wheel':19,
        'Defence Curl':22,
        'Flame Charge':28,
        'Swift':31,
        'Lava Plume':37,
        'Flamethrower':40,
        'Inferno':46,
        'Double-Edge':55,
        'Burn Up':58,
        'Eruption':64
    },
    '156':{
        'Leer':1,
        'Tackle':1,
        'Smokescreen':1,
        'Ember':1,
        'Quick Attack':1,
        'Flame Wheel':20,
        'Defence Curl':24,
        'Flame Charge':31,
        'Swift':35,
        'Lava Plume':42,
        'Flamethrower':46,
        'Inferno':53,
        'Double-Edge':64,
        'Burn Up':68,
        'Eruption':75
    },
    '157':{
        'Leer':1,
        'Tackle':1,
        'Smokescreen':1,
        'Ember':1,
        'Quick Attack':1,
        'Flame Wheel':1,
        'Defence Curl':1,
        'Flame Charge':1,
        'Swift':1,
        'Lava Plume':43,
        'Flamethrower':48,
        'Inferno':56,
        'Double-Edge':69,
        'Burn Up':74,
        'Eruption':82
    },
    '158':{
        'Leer':1,
        'Scratch':1,
        'Water Gun':6,
        'Bite':13,
        'Scary Face':15,
        'Ice Fang':20,
        'Crunch':27,
        'Chip Away':29,
        'Slash':34,
        'Screech':36,
        'Thrash':41,
        'Aqua Tail':43,
        'Superpower':48,
        'Hydro Pump':50
    },
    '159':{
        'Leer':1,
        'Scratch':1,
        'Water Gun':1,
        'Bite':1,
        'Scary Face':1,
        'Ice Fang':21,
        'Crunch':30,
        'Chip Away':33,
        'Slash':39,
        'Screech':42,
        'Thrash':48,
        'Aqua Tail':51,
        'Superpower':57,
        'Hydro Pump':60
    },
    '160':{
        'Agility':1,
        'Leer':1,
        'Scratch':1,
        'Water Gun':1,
        'Bite':1,
        'Scary Face':1,
        'Ice Fang':21,
        'Crunch':32,
        'Chip Away':37,
        'Slash':45,
        'Screech':50,
        'Thrash':58,
        'Aqua Tail':63,
        'Superpower':71,
        'Hydro Pump':76
    },
    '161':{
        'Scratch':1,
        'Defence Curl':4,
        'Quick Attack':7,
        'Fury Swipes':13,
        'Slam':25,
        'Rest':28,
        'Sucker Punch':31,
        'Amnesia':36,
        'Hyper Voice':47
    },
    '162':{
        'Agility':1,
        'Coil':1,
        'Scratch':1,
        'Defence Curl':1,
        'Quick Attack':1,
        'Fury Swipes':1,
        'Slam':28,
        'Rest':32,
        'Sucker Punch':36,
        'Amnesia':42,
        'Hyper Voice':56
    },
    '163':{
        'Growl':1,
        'Tackle':1,
        'Hypnosis':4,
        'Peck':7,
        'Confusion':10,
        'Echoed Voice':13,
        'Zen Headbutt':16,
        'Extrasensory':22,
        'Take Down':25,
        'Air Slash':31,
        'Uproar':34,
        'Roost':37,
        'Moonblast':40,
        'Dream Eater':46
    },
    '164':{
        'Growl':1,
        'Tackle':1,
        'Hypnosis':1,
        'Peck':1,
        'Confusion':1,
        'Echoed Voice':1,
        'Zen Headbutt':1,
        'Extrasensory':23,
        'Take Down':27,
        'Air Slash':35,
        'Uproar':39,
        'Roost':43,
        'Moonblast':47,
        'Dream Eater':55
    },
    '165':{
        'Tackle':1,
        'Supersonic':5,
        'Swift':8,
        'Mach Punch':15,
        'Silver Wind':19,
        'Comet Punch':22,
        'Agility':29,
        'Bug Buzz':33,
        'Air Slash':36,
        'Double-Edge':40
    },
    '166':{
        'Tackle':1,
        'Supersonic':1,
        'Swift':1,
        'Mach Punch':1,
        'Silver Wind':20,
        'Comet Punch':23,
        'Agility':33,
        'Bug Buzz':38,
        'Air Slash':42,
        'Double-Edge':47
    },
    '167':{
        'Constrict':1,
        'Poison Sting':1,
        'String Shot':1,
        'Absorb':5,
        'Scary Face':12,
        'Shadow Sneak':19,
        'Fury Swipes':22,
        'Sucker Punch':26,
        'Agility':33,
        'Pin Missile':36,
        'Psychic':40,
        'Poison Jab':43,
        'Cross Poison':47,
        'Toxic Thread':54
    },
    '168':{
        'Bug Bite':1,
        'Fell Stinger':1,
        'Swords Dance':1,
        'Constrict':1,
        'Poison Sting':1,
        'String Shot':1,
        'Absorb':1,
        'Scary Face':1,
        'Shadow Sneak':1,
        'Fury Swipes':23,
        'Sucker Punch':28,
        'Agility':37,
        'Pin Missile':41,
        'Psychic':46,
        'Poison Jab':50,
        'Cross Poison':55,
        'Toxic Thread':63
    },
    '169':{
        'Absorb':1,
        'Astonish':1,
        'Bite':1,
        'Cross Poison':1,
        'Screech':1,
        'Supersonic':1,
        'Wing Attack':1,
        'Confuse Ray':1,
        'Air Cutter':1,
        'Swift':24,
        'Poison Fang':27,
        'Leech Life':35,
        'Venoshock':43,
        'Air Slash':48
    },
    '170':{
        'Bubble':1,
        'Supersonic':1,
        'Thunder Wave':6,
        'Water Gun':12,
        'Confuse Ray':17,
        'Bubble Beam':20,
        'Spark':23,
        'Signal Beam':28,
        'Discharge':34,
        'Take Down':39,
        'Aqua Ring':42,
        'Hydro Pump':45,
        'Charge':50
    },
    '171':{
        'Bubble':1,
        'Eerie Impulse':1,
        'Supersonic':1,
        'Thunder Wave':1,
        'Water Gun':1,
        'Confuse Ray':1,
        'Bubble Beam':1,
        'Spark':1,
        'Signal Beam':29,
        'Discharge':37,
        'Take Down':43,
        'Aqua Ring':47,
        'Hydro Pump':51,
        'Charge':58
    },
    '172':{
        'Charm':1,
        'Thunder Shock':1,
        'Tail Whip':5,
        'Sweet Kiss':10,
        'Nasty Plot':13,
        'Thunder Wave':20
    },
    '173':{
        'Charm':1,
        'Pound':1,
        'Sing':7,
        'Sweet Kiss':10,
        'Magical Leaf':16
    },
    '174':{
        'Charm':1,
        'Sing':1,
        'Defence Curl':3,
        'Pound':5,
        'Sweet Kiss':9
    },
    '175':{
        'Charm':1,
        'Growl':1,
        'Sweet Kiss':9,
        'Yawn':13,
        'Wish':29,
        'Ancient Power':33,
        'Double-Edge':45
    },
    '176':{
        'Charm':1,
        'Magical Leaf':1,
        'Growl':1,
        'Sweet Kiss':9,
        'Yawn':13,
        'Fairy Wind':14,
        'Wish':29,
        'Ancient Power':33,
        'Double-Edge':45
    },
    '177':{
        'Leer':1,
        'Peck':1,
        'Stored Power':17,
        'Ominous Wind':20,
        'Confuse Ray':23,
        'Wish':28,
        'Psychic':33,
        'Future Sight':44
    },
    '178':{
        'Leer':1,
        'Peck':1,
        'Stored Power':1,
        'Ominous Wind':1,
        'Confuse Ray':1,
        'Wish':29,
        'Psychic':35,
        'Future Sight':49
    },
    '179':{
        'Growl':1,
        'Tackle':1,
        'Thunder Wave':4,
        'Thunder Shock':8,
        'Cotton Spore':11,
        'Charge':15,
        'Take Down':18,
        'Confuse Ray':25,
        'Power Gem':29,
        'Discharge':32,
        'Cotton Guard':36,
        'Signal Beam':39,
        'Thunder':46
    },
    '180':{
        'Growl':1,
        'Tackle':1,
        'Thunder Wave':1,
        'Thunder Shock':1,
        'Cotton Spore':1,
        'Charge':16,
        'Take Down':20,
        'Confuse Ray':29,
        'Power Gem':34,
        'Discharge':38,
        'Cotton Guard':43,
        'Signal Beam':47,
        'Thunder':56
    },
    '181':{
        'Fire Punch':1,
        'Growl':1,
        'Tackle':1,
        'Thunder Punch':1,
        'Thunder Wave':1,
        'Thunder Shock':1,
        'Zap Cannon':1,
        'Cotton Spore':1,
        'Charge':1,
        'Confuse Ray':1,
        'Power Gem':35,
        'Discharge':40,
        'Cotton Guard':46,
        'Signal Beam':51,
        'Thunder':62,
        'Dragon Pulse':65
    },
    '182':{
        'Leaf Blade':1,
        'Magical Leaf':1,
        'Mega Drain':1,
        'Stun Spore':1,
        'Quiver Dance':39,
        'Petal Blizzard':49,
        'Petal Dance':59,
        'Leaf Storm':69
    },
    '183':{
        'Tackle':1,
        'Water Gun':1,
        'Tail Whip':2,
        'Bubble':7,
        'Defence Curl':10,
        'Rollout':10,
        'Bubble Beam':13,
        'Aqua Tail':20,
        'Play Rough':23,
        'Aqua Ring':28,
        'Double-Edge':37,
        'Superpower':40,
        'Hydro Pump':47
    },
    '184':{
        'Tackle':1,
        'Water Gun':1,
        'Tail Whip':1,
        'Bubble':1,
        'Defence Curl':1,
        'Rollout':1,
        'Bubble Beam':1,
        'Aqua Tail':21,
        'Play Rough':25,
        'Aqua Ring':31,
        'Double-Edge':42,
        'Superpower':46,
        'Hydro Pump':55
    },
    '185':{
        'Rock Throw':1,
        'Slam':1,
        'Wood Hammer':1,
        'Feint Attack':19,
        'Tearful Look':22,
        'Rock Tomb':26,
        'Rock Slide':33,
        'Sucker Punch':40,
        'Double-Edge':43,
        'Stone Edge':47,
        'Hammer Arm':50,
        'Head Smash':54
    },
    '186':{
        'Bubble Beam':1,
        'Double Slap':1,
        'Hypnosis':1,
        'Perish Song':1,
        'Swagger':27,
        'Bounce':37,
        'Hyper Voice':48
    },
    '187':{
        'Absorb':1,
        'Splash':1,
        'Synthesis':4,
        'Tail Whip':6,
        'Tackle':8,
        'Fairy Wind':10,
        'Poison Powder':12,
        'Stun Spore':14,
        'Sleep Powder':16,
        'Bullet Seed':19,
        'Mega Drain':25,
        'Acrobatics':28,
        'Cotton Spore':34,
        'U-Turn':37,
        'Giga Drain':43,
        'Bounce':46,
        'Memento':49
    },
    '188':{
        'Absorb':1,
        'Splash':1,
        'Synthesis':1,
        'Tail Whip':1,
        'Tackle':1,
        'Fairy Wind':1,
        'Poison Powder':1,
        'Stun Spore':1,
        'Sleep Powder':1,
        'Bullet Seed':20,
        'Mega Drain':28,
        'Acrobatics':32,
        'Cotton Spore':40,
        'U-Turn':44,
        'Giga Drain':52,
        'Bounce':56,
        'Memento':60
    },
    '189':{
        'Absorb':1,
        'Splash':1,
        'Synthesis':1,
        'Tail Whip':1,
        'Tackle':1,
        'Fairy Wind':1,
        'Poison Powder':1,
        'Stun Spore':1,
        'Sleep Powder':1,
        'Bullet Seed':1,
        'Mega Drain':29,
        'Acrobatics':34,
        'Cotton Spore':44,
        'U-Turn':49,
        'Giga Drain':59,
        'Bounce':64,
        'Memento':69
    },
    '190':{
        'Scratch':1,
        'Tail Whip':1,
        'Sand Attack':4,
        'Astonish':8,
        'Tickle':15,
        'Fury Swipes':18,
        'Swift':22,
        'Screech':25,
        'Agility':29,
        'Double Hit':32,
        'Nasty Plot':36
    },
    '191':{
        'Absorb':1,
        'Growth':1,
        'Grass Whistle':7,
        'Mega Drain':10,
        'Razor Leaf':16,
        'Giga Drain':22,
        'Solar Beam':34,
        'Double-Edge':37,
        'Seed Bomb':43
    },
    '192':{
        'Absorb':1,
        'Flower Shield':1,
        'Growth':1,
        'Pound':1,
        'Grass Whistle':7,
        'Mega Drain':10,
        'Razor Leaf':16,
        'Giga Drain':22,
        'Solar Beam':34,
        'Double-Edge':37,
        'Leaf Storm':43,
        'Petal Blizzard':50
    },
    '193':{
        'Tackle':1,
        'Quick Attack':6,
        'Supersonic':22,
        'Uproar':27,
        'Pursuit':30,
        'Ancient Power':33,
        'Hypnosis':38,
        'Wing Attack':43,
        'Screech':46,
        'U-Turn':49,
        'Air Slash':54,
        'Bug Buzz':57
    },
    '194':{
        'Tail Whip':1,
        'Water Gun':1,
        'Mud Shot':9,
        'Slam':15,
        'Mud Bomb':19,
        'Amnesia':23,
        'Yawn':29,
        'Earthquake':33,
        'Muddy Water':47
    },
    '195':{
        'Tail Whip':1,
        'Water Gun':1,
        'Mud Shot':1,
        'Slam':1,
        'Mud Bomb':1,
        'Amnesia':24,
        'Yawn':31,
        'Earthquake':36,
        'Muddy Water':53
    },
    '196':{
        'Confusion':1,
        'Tackle':1,
        'Tail Whip':1,
        'Sand Attack':5,
        'Baby-Doll Eyes':9,
        'Quick Attack':13,
        'Swift':17,
        'Psybeam':20,
        'Future Sight':25,
        'Psychic':37
    },
    '197':{
        'Pursuit':1,
        'Tackle':1,
        'Tail Whip':1,
        'Sand Attack':5,
        'Baby-Doll Eyes':9,
        'Quick Attack':13,
        'Confuse Ray':17,
        'Feint Attack':20,
        'Future Sight':25,
        'Screech':29,
        'Moonlight':33,
        'Mean Look':37
    },
    '198':{
        'Peck':1,
        'Astonish':1,
        'Pursuit':5,
        'Wing Attack':15,
        'Assurance':25,
        'Feint Attack':35,
        'Mean Look':41,
        'Sucker Punch':55,
        'Future Sight':25,
        'Psychic':37
    },
    '199':{
        'Hidden Power':1,
        'Power Gem':1,
        'Tackle':1,
        'Yawn':1,
        'Growl':5,
        'Water Gun':9,
        'Confusion':14,
        'Headbutt':23,
        'Water Pulse':28,
        'Zen Headbutt':32,
        'Nasty Plot':36,
        'Swagger':41,
        'Psychic':45
    },
    '200':{
        'Growl':1,
        'Psywave':1,
        'Astonish':10,
        'Confuse Ray':14,
        'Mean Look':19,
        'Hex':23,
        'Psybeam':28,
        'Payback':37,
        'Shadow Ball':46,
        'Power Gem':55
    },
    '201':{
        'Hidden Power':1
    },
    '202':{
        'Amnesia':1,
        'Charm':1,
        'Splash':1
    },
    '203':{
        'Astonish':1,
        'Confusion':1,
        'Growl':1,
        'Tackle':1,
        'Assurance':10,
        'Stomp':14,
        'Psybeam':19,
        'Agility':23,
        'Double Hit':28,
        'Zen Headbutt':32,
        'Crunch':37,
        'Nasty Plot':46,
        'Psychic':50
    },
    '204':{
        'Tackle':1,
        'Self-Destruct':6,
        'Bug Bite':9,
        'Take Down':12,
        'Rapid Spin':17,
        'Payback':31,
        'Explosion':34,
        'Iron Defence':39,
        'Double-Edge':45
    },
    '205':{
        'Automotize':1,
        'Mirror Shot':1,
        'Tackle':1,
        'Self-Destruct':1,
        'Bug Bite':1,
        'Take Down':1,
        'Rapid Spin':1,
        'Payback':32,
        'Explosion':36,
        'Iron Defence':41,
        'Double-Edge':50,
        'Zap Cannon':60
    },
    '206':{
        'Defence Curl':1,
        'Rollout':3,
        'Pursuit':8,
        'Screech':11,
        'Mud-Slap':13,
        'Yawn':16,
        'Ancient Power':18,
        'Body Slam':21,
        'Drill Run':23,
        'Roost':26,
        'Take Down':28,
        'Coil':31,
        'Dig':33,
        'Glare':36,
        'Double-Edge':38,
        'Air Slash':43,
        'Dragon Rush':46
    },
    '207':{
        'Poison Sting':1,
        'Sand Attack':4,
        'Harden':7,
        'Knock':10,
        'Quick Attack':13,
        'Fury Cutter':16,
        'Feint Attack':19,
        'Acrobatics':22,
        'Slash':27,
        'U-Turn':30,
        'Screech':35,
        'X-Scissor':40,
        'Sky Uppercut':45,
        'Swords Dance':50,
        'Guillotine':55
    },
    '208':{
        'Fire Fang':1,
        'Harden':1,
        'Ice Fang':1,
        'Tackle':1,
        'Thunder Fang':1,
        'Rock Throw':7,
        'Rock Tomb':10,
        'Autotomize':19,
        'Smack Down':22,
        'Dragon Breath':25,
        'Slam':28,
        'Screech':31,
        'Rock Slide':34,
        'Crunch':37,
        'Iron Tail':40,
        'Dig':43,
        'Stone Edge':46,
        'Double-Edge':49
    },
    '209':{
        'Charm':1,
        'Fire Fang':1,
        'Ice Fang':1,
        'Scary Face':1,
        'Tail Whip':1,
        'Tackle':1,
        'Thunder Fang':1,
        'Bite':7,
        'Lick':13,
        'Headbutt':19,
        'Play Rough':43,
        'Payback':51,
        'Crunch':59,
        'Outrage':67
    },
    '210':{
        'Charm':1,
        'Fire Fang':1,
        'Ice Fang':1,
        'Scary Face':1,
        'Tail Whip':1,
        'Tackle':1,
        'Thunder Fang':1,
        'Bite':7,
        'Lick':13,
        'Headbutt':19,
        'Play Rough':37,
        'Payback':43,
        'Crunch':49
    },
    '211':{
        'Poison Sting':1,
        'Tackle':1,
        'Water Gun':1,
        'Harden':9,
        'Bubble':13,
        'Rollout':17,
        'Revenge':29,
        'Dragon Breath':25,
        'Slam':28,
        'Brine':33,
        'Pin Missile':37,
        'Take Down':41,
        'Aqua Tail':45,
        'Poison Jab':49,
        'Stone Edge':46,
        'Hydro Pump':57,
        'Fell Stinger':60
    },
    '212':{
        'Bullet Punch':1,
        'Leer':1,
        'Quick Attack':1,
        'Pursuit':9,
        'False Swipe':13,
        'Agility':17,
        'Metal Claw':21,
        'Fury Cutter':25,
        'Slash':29,
        'Razor Wind':33,
        'Iron Defence':37,
        'X-Scissor':41,
        'Night Slash':45,
        'Double Hit':49,
        'Iron Head':50,
        'Swords Dance':57
    },
    '213':{
        'Constrict':1,
        'Rollout':1,
        'Withdraw':1,
        'Struggle Bug':12,
        'Rest':20,
        'Rock Throw':23,
        'Shell Smash':34,
        'Rock Slide':38,
        'Bug Bite':42,
        'Stone Edge':49
    },
    '214':{
        'Arm Thrust':1,
        'Bullet Seed':1,
        'Horn Attack':1,
        'Leer':1,
        'Night Slash':1,
        'Tackle':1,
        'Aerial Ace':10,
        'Chip Away':16,
        'Fury Cutter':25,
        'Brick Break':28,
        'Pin Missile':31,
        'Take Down':34,
        'Megahorn':37,
        'Close Combat':43
    },
    '215':{
        'Leer':1,
        'Scratch':1,
        'Quick Attack':8,
        'Feint Attack':10,
        'Icy Wind':14,
        'Fury Swipes':16,
        'Agility':20,
        'Metal Claw':22,
        'Hone Claws':25,
        'Screech':32,
        'Slash':35,
        'Ice Shard':47
    },
    '216':{
        'Baby-Doll Eyes':1,
        'Covet':1,
        'Fake Tears':1,
        'Lick':1,
        'Scratch':1,
        'Fury Swipes':8,
        'Feint Attack':15,
        'Play Nice':25,
        'Slash':29,
        'Charm':36,
        'Rest':43,
        'Thrash':50
    },
    '217':{
        'Covet':1,
        'Fake Tears':1,
        'Lick':1,
        'Scratch':1,
        'Fury Swipes':1,
        'Feint Attack':1,
        'Play Nice':1,
        'Slash':1,
        'Charm':38,
        'Rest':47,
        'Thrash':58,
        'Hammer Arm':67
    },
    '218':{
        'Smog':1,
        'Yawn':1,
        'Ember':6,
        'Rock Throw':8,
        'Harden':13,
        'Incinerate':15,
        'Ancient Power':22,
        'Flame Burst':27,
        'Rock Slide':29,
        'Lava Plume':34,
        'Amnesia':36,
        'Body Slam':41,
        'Recover':43,
        'Flamethrower':48,
        'Earth Power':50
    },
    '219':{
        'Smog':1,
        'Yawn':1,
        'Ember':1,
        'Shell Smash':1,
        'Rock Throw':1,
        'Harden':1,
        'Incinerate':1,
        'Ancient Power':1,
        'Flame Burst':1,
        'Rock Slide':1,
        'Lava Plume':1,
        'Amnesia':1,
        'Body Slam':43,
        'Recover':47,
        'Flamethrower':54,
        'Earth Power':58
    }
}

tm = {
    '001': {}
}